export const ADMINISTRACION_MODULES = [
  {
    id: 'alertas',
    icon: '🔔',
    title: 'Alertas Proactivas',
    description: 'Configurá alertas automáticas por vencimientos, stock y pendientes',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['alertas', 'notificaciones', 'vencimiento', 'stock', 'automatico'],
    steps: [
      {
        title: 'Configurar alertas',
        duration: '4 min',
        difficulty: 'Media',
        description: 'El módulo de alertas proactivas te permite configurar notificaciones automáticas para distintos eventos del sistema.',
        instructions: [
          'Andá a Alertas Proactivas en Administración',
          'Activá o desactivá cada tipo de alerta',
          'Configurá los días de anticipación para vencimientos',
          'Establecé el umbral de stock mínimo',
          'Agregá emails destinatarios para notificaciones',
          'Guardá los cambios',
        ],
        tips: [
          'Las alertas pueden mostrarse como banner en el dashboard y/o enviarse por email',
          'Los tipos disponibles son: garantía de activo, stock bajo, pendiente vencido',
        ],
      },
    ],
  },
  {
    id: 'importar',
    icon: '📥',
    title: 'Importar Datos',
    description: 'Cargá datos masivos desde Excel o CSV al sistema',
    color: '#64748b',
    category: 'administracion',
    keywords: ['importar', 'excel', 'csv', 'masivo', 'carga'],
    steps: [
      {
        title: 'Importar datos desde Excel',
        duration: '5 min',
        difficulty: 'Media',
        description: 'El módulo de importación permite cargar grandes volúmenes de datos de cualquier módulo desde archivos Excel.',
        instructions: [
          'Andá a Importar Datos',
          'Seleccioná el tipo de datos a importar',
          'Descargá la plantilla de ejemplo',
          'Completá la plantilla con tus datos',
          'Subí el archivo en el paso "Subir archivo"',
          'Mapeá las columnas con los campos del sistema',
          'Revisá la vista previa',
          'Confirmá la importación',
        ],
        tips: [
          'Siempre usá la plantilla descargada para evitar errores de formato',
          'Podés importar empleados, materiales, proyectos, pendientes y más',
        ],
        important: 'Revisá siempre la vista previa antes de confirmar para detectar errores en los datos.',
      },
    ],
  },
  {
    id: 'automatizaciones',
    icon: '⚡',
    title: 'Automatizaciones',
    description: 'Configurá tareas programadas y alertas automáticas del sistema',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['automatizaciones', 'programado', 'cron', 'tareas', 'alertas', 'automático'],
    steps: [
      {
        title: 'Gestionar automatizaciones',
        duration: '4 min',
        difficulty: 'Media',
        description: 'El módulo de automatizaciones ejecuta tareas en segundo plano: generación de certificados mensuales, alertas proactivas y procesamiento de rutinas.',
        instructions: [
          'Andá a Automatizaciones en el menú lateral',
          'Revisá el listado de automatizaciones activas e inactivas',
          'Cada una muestra: nombre, función, última ejecución y estado',
          'Activá o desactivá una automatización con el interruptor',
          'Revisá el historial de ejecuciones y errores',
          'Las automatizaciones críticas no se pueden desactivar',
        ],
        tips: [
          'La generación mensual de certificados corre automáticamente cada mes',
          'El procesamiento de rutinas genera órdenes según la frecuencia de cada rutina',
          'Si una automatización falla, revisá el mensaje de error en el historial',
        ],
        important: 'Las automatizaciones se ejecutan en horarios programados (UTC) y pueden tardar unos minutos en completarse.',
      },
    ],
  },
  {
    id: 'permisos',
    icon: '🔒',
    title: 'Control de Acceso',
    description: 'Definí roles y permisos por módulo para cada tipo de usuario',
    color: '#64748b',
    category: 'administracion',
    keywords: ['permisos', 'roles', 'acceso', 'seguridad', 'usuarios', 'configuración'],
    steps: [
      {
        title: 'Configurar roles y permisos',
        duration: '5 min',
        difficulty: 'Avanzada',
        description: 'El control de acceso permite definir qué módulos y acciones puede ver cada rol (admin, gerente, supervisor, técnico, viewer).',
        instructions: [
          'Andá a Control de Acceso en Administración',
          'Revisá los roles disponibles y su descripción',
          'Para cada rol, configurá los permisos por módulo',
          'Las acciones disponibles son: leer, crear, editar, eliminar, exportar, aprobar',
          'Los admins de plataforma tienen acceso total sin restricciones',
          'Guardá los cambios al finalizar',
        ],
        tips: [
          'Los usuarios sin permisos configurados solo ven Dashboard y Centro de Aprendizaje',
          'El diagnóstico de vinculación muestra si un usuario está correctamente asociado a su empleado',
          'Los cambios de permisos se aplican inmediatamente al próximo inicio de sesión',
        ],
        important: 'Solo los administradores pueden modificar los permisos de los roles.',
      },
    ],
  },
  {
    id: 'auditoria',
    icon: '📝',
    title: 'Auditoría',
    description: 'Revisá el registro de todas las acciones sensibles del sistema',
    color: '#64748b',
    category: 'administracion',
    keywords: ['auditoría', 'log', 'registro', 'acciones', 'trazabilidad', 'seguridad'],
    steps: [
      {
        title: 'Consultar el registro de auditoría',
        duration: '3 min',
        difficulty: 'Media',
        description: 'El módulo de auditoría registra automáticamente todas las acciones sensibles: creación, edición y eliminación de registros, accesos y cambios de configuración.',
        instructions: [
          'Andá a Auditoría en Administración',
          'Revisá el listado cronológico de acciones',
          'Filtrá por usuario, módulo, tipo de acción o fecha',
          'Cada registro muestra: usuario, acción, módulo, detalle y fecha/hora',
          'Usá el diagnóstico del sistema para verificar el estado de la auditoría',
        ],
        tips: [
          'Los registros de auditoría no se pueden eliminar ni modificar',
          'El sistema audita automáticamente cambios en permisos, certificados y configuraciones',
        ],
      },
    ],
  },
  {
    id: 'seguridad',
    icon: '🛡️',
    title: 'Centro de Seguridad',
    description: 'Gestioná autenticación de dos factores, backups y cifrado',
    color: '#ef4444',
    category: 'seguridad',
    keywords: ['seguridad', '2fa', 'doble factor', 'backup', 'cifrado', 'sesiones', 'sospechosa'],
    steps: [
      {
        title: 'Configurar doble factor (2FA)',
        duration: '4 min',
        difficulty: 'Media',
        description: 'La autenticación de dos factores agrega una capa extra de seguridad al requerir un código además de la contraseña.',
        instructions: [
          'Andá a Centro de Seguridad en Administración',
          'Abrí la sección "Doble Factor de Autenticación"',
          'Hacé clic en "Activar 2FA"',
          'Escaneá el código QR con tu app de autenticación (Google Authenticator, Authy)',
          'Ingresá el código de verificación generado',
          'Guardá los códigos de respaldo en un lugar seguro',
        ],
        tips: [
          'Los códigos de respaldo sirven si perdés acceso a tu app de autenticación',
          '2FA es obligatorio para roles administrativos',
        ],
        important: 'Si perdés el acceso a tu app de autenticación y no tenés códigos de respaldo, contactá al administrador.',
      },
      {
        title: 'Backups y actividad sospechosa',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Gestioná backups cifrados y monitoreá actividad inusual en el sistema.',
        instructions: [
          'En el Centro de Seguridad, abrí "Backups Cifrados"',
          'Generá un backup manual o revisá los automáticos',
          'Los backups se cifran con contraseña — guardala en lugar seguro',
          'Abrí "Actividad Sospechosa" para revisar intentos de acceso anómalos',
          'Revisá las sesiones activas y cerrá las que no reconozcas',
          'El sistema marca automáticamente accesos desde ubicaciones inusuales',
        ],
        tips: [
          'Los backups automáticos se generan periódicamente',
          'Cerrá sesiones que no reconozcas inmediatamente',
          'El monitoreo de actividad sospechosa ayuda a detectar accesos no autorizados',
        ],
      },
    ],
  },
];