export const COMERCIAL_MODULES = [
  {
    id: 'proveedores',
    icon: '🚛',
    title: 'Proveedores',
    description: 'Administrá el directorio de proveedores de materiales y servicios',
    color: '#ec4899',
    category: 'administracion',
    keywords: ['proveedores', 'contactos', 'valoración', 'rubro', 'cuit'],
    steps: [
      {
        title: 'Registrar un proveedor',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Mantené actualizado el directorio de proveedores con sus datos de contacto y valoración de desempeño.',
        instructions: [
          'Andá a Proveedores',
          'Hacé clic en "Nuevo"',
          'Completá: nombre/razón social, CUIT',
          'Seleccioná el rubro principal',
          'Agregá contacto, email y teléfono',
          'Asigná una valoración del 1 al 5',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'La valoración te ayuda a priorizar proveedores confiables',
          'Usá las notas para condiciones de pago o acuerdos especiales',
        ],
        example: 'Proveedor: "Ferreterías del Sur" | Rubro: Materiales | Valoración: ★★★★☆',
      },
    ],
  },
  {
    id: 'presupuestos',
    icon: '💵',
    title: 'Presupuestos',
    description: 'Creá cotizaciones y presupuestos para enviar a clientes',
    color: '#f97316',
    category: 'administracion',
    keywords: ['presupuesto', 'cotización', 'cliente', 'items', 'precio'],
    steps: [
      {
        title: 'Crear un presupuesto',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Los presupuestos son cotizaciones que se envían al cliente antes de iniciar un trabajo.',
        instructions: [
          'Andá a Presupuestos',
          'Hacé clic en "Nuevo Presupuesto"',
          'Seleccioná el cliente',
          'Agregá ítems con descripción, cantidad y precio unitario',
          'El total se calcula automáticamente',
          'Establecé fecha de validez',
          'Guardá y exportá en PDF para enviar',
        ],
        tips: [
          'Un presupuesto aprobado puede convertirse en factura',
          'Incluí márgenes razonables en los precios',
        ],
      },
    ],
  },
  {
    id: 'presupuestos-obra',
    icon: '📐',
    title: 'Presupuestos de Obra (PCP)',
    description: 'Creá presupuestos detallados usando el preciario ministerial',
    color: '#06b6d4',
    category: 'administracion',
    keywords: ['presupuesto', 'preciario', 'PCP', 'rubro', 'coeficiente', 'ministerio'],
    steps: [
      {
        title: 'Crear un presupuesto PCP',
        duration: '6 min',
        difficulty: 'Media',
        description: 'Los presupuestos PCP se arman en base al preciario ministerial, con ítems agrupados por rubro y cálculo automático de coeficientes.',
        instructions: [
          'Andá a Presupuestos Obra',
          'Hacé clic en "Nuevo Presupuesto"',
          'Completá: código, título, cliente, licitación, escuela',
          'Configurá los coeficientes de pase y oferta',
          'Seleccioná la commune del preciario',
          'En la grilla PCP, buscá ítems del preciario y agregálos',
          'Ingresá la cantidad para cada ítem',
          'El sistema calcula automáticamente los totales',
        ],
        tips: [
          'El coeficiente de pase por defecto es 1.6504 y el de oferta 1.38',
          'Podés agrupar ítems por rubros para organizar mejor el presupuesto',
        ],
        important: 'Seleccioná la commune correcta del preciario para que los precios sean los correspondientes.',
      },
      {
        title: 'Exportar y Plan de Trabajos',
        duration: '3 min',
        difficulty: 'Media',
        description: 'Exportá el PCP completo a Excel y generá automáticamente el Plan de Trabajos.',
        instructions: [
          'Desde el presupuesto, hacé clic en "Plan de Trabajos"',
          'El sistema distribuye automáticamente los ítems en semanas',
          'Ajustá la distribución si es necesario',
          'Hacé clic en "Exportar Excel" para el PCP completo',
        ],
        tips: [
          'El archivo Excel incluye todas las hojas reglamentarias',
          'El Plan de Trabajos puede editarse antes de exportar',
        ],
      },
    ],
  },
  {
    id: 'certificados',
    icon: '🏆',
    title: 'Certificados de Obra',
    description: 'Generá certificados de avance de obra a partir de presupuestos aprobados',
    color: '#eab308',
    category: 'administracion',
    keywords: ['certificados', 'avance', 'ada', 'obra', 'facturar'],
    steps: [
      {
        title: 'Generar un certificado',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Los certificados de obra documentan el avance ejecutado en un período y sirven de base para la facturación.',
        instructions: [
          'Andá a Certificados',
          'Seleccioná el presupuesto PCP base',
          'Ingresá el % de avance del período a certificar',
          'El sistema calcula el monto a certificar automáticamente',
          'Revisá los ítems certificados',
          'Exportá el certificado en PDF',
        ],
        tips: [
          'Podés subir el ADA (Acta de Aprobación) desde el módulo',
          'Los certificados se generan sobre el presupuesto PCP aprobado',
        ],
      },
    ],
  },
  {
    id: 'facturacion',
    icon: '💰',
    title: 'Facturación',
    description: 'Creá y gestioná facturas y registros de cobranza',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['facturas', 'pagos', 'cobranza', 'vencimiento'],
    steps: [
      {
        title: 'Crear una factura',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Las facturas formalizan los cobros y quedan registradas para el seguimiento financiero.',
        instructions: [
          'Andá a Facturación',
          'Hacé clic en "Nueva Factura"',
          'Seleccioná el cliente',
          'Agregá ítems con descripción, cantidad y precio',
          'Establecé fecha de vencimiento',
          'Guardá y emitila',
        ],
        tips: [
          'Exportá en PDF para enviar al cliente',
          'Las facturas vencidas generan alerta en el dashboard',
        ],
        important: 'Una vez emitida, la factura no se puede editar. Guardá siempre el PDF.',
      },
      {
        title: 'Registrar pagos',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Marcá los pagos recibidos para mantener las cuentas al día.',
        instructions: [
          'Abrí la factura pendiente de cobro',
          'Hacé clic en "Registrar Pago"',
          'Ingresá el monto pagado y método',
          'Guardá',
        ],
        tips: [
          'Los pagos parciales calculan el saldo automáticamente',
        ],
      },
    ],
  },
  {
    id: 'finanzas',
    icon: '📊',
    title: 'Finanzas',
    description: 'Analizá el flujo de caja y la rentabilidad de proyectos',
    color: '#22c55e',
    category: 'administracion',
    keywords: ['finanzas', 'flujo', 'caja', 'rentabilidad', 'gastos', 'ingresos'],
    steps: [
      {
        title: 'Explorar el módulo de finanzas',
        duration: '4 min',
        difficulty: 'Media',
        description: 'El módulo de finanzas muestra el resumen financiero, flujo de caja y rentabilidad por proyecto.',
        instructions: [
          'Andá a Finanzas en el menú lateral',
          'Revisá el Resumen Financiero con ingresos y egresos',
          'Explorá el Flujo de Caja para ver movimientos en el tiempo',
          'Analizá la Rentabilidad por Proyecto',
          'Filtrá por período para ver distintos rangos',
        ],
        tips: [
          'Un margen sano está entre 20-30%',
          'Identificá proyectos menos rentables para optimizar costos',
        ],
      },
    ],
  },
  {
    id: 'certificacion-obras',
    icon: '📋',
    title: 'Certificación de Obras',
    description: 'Controlá el avance y estado de cobro de obras en cada ciclo mensual',
    color: '#eab308',
    category: 'administracion',
    keywords: ['certificación', 'obras', 'avance', 'ciclo', 'cobro', 'MEIN', 'MTOM', 'SAP'],
    steps: [
      {
        title: 'Gestionar el ciclo de certificación',
        duration: '5 min',
        difficulty: 'Media',
        description: 'El módulo de Certificación de Obras centraliza el seguimiento de avance y estado de cobro de cada obra en el ciclo mensual activo.',
        instructions: [
          'Andá a Certificación de Obras',
          'Revisá las obras del ciclo activo',
          'Filtrá por commune, estado de cobro o jefe de sitio',
          'Hacé clic en una obra para editar su avance, estado y observaciones',
          'Los estados de cobro son: Listo Certificar, Faltan Actas, Pendiente, Observado, Falta Aprobar MEIN',
          'Al cerrar el ciclo, los registros se archivan automáticamente',
          'Importá obras nuevas desde Excel con el botón "Importar"',
        ],
        tips: [
          'Usá el campo "Tramo de certificación" para distinguir primer y segundo 50%',
          'Las obras observadas tienen un campo de motivo para documentar el problema',
          'Exportá el resumen del ciclo a PDF desde el botón de exportar',
        ],
      },
    ],
  },
  {
    id: 'aprobacion-certificados',
    icon: '✅',
    title: 'Aprobación de Certificados',
    description: 'Flujo de solicitud, revisión y firma gerencial de certificados de obra',
    color: '#22c55e',
    category: 'administracion',
    keywords: ['aprobación', 'firma', 'gerente', 'certificado', 'solicitud', 'digital'],
    steps: [
      {
        title: 'Crear una solicitud de certificado',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Los jefes de sitio envían solicitudes de certificado que luego revisa y aprueba gerencia.',
        instructions: [
          'Andá a Aprobación de Certificados',
          'Hacé clic en "Nueva Solicitud"',
          'Completá: título, establecimiento, período, descripción del trabajo',
          'Ingresá el monto solicitado y % de avance',
          'Adjuntá fotos y documentos de respaldo',
          'Hacé clic en "Enviar Solicitud"',
        ],
        tips: [
          'Las solicitudes enviadas llegan a la vista de revisión gerencial',
          'Podés guardar como borrador antes de enviar',
        ],
      },
      {
        title: 'Revisar y aprobar (gerencia)',
        duration: '3 min',
        difficulty: 'Media',
        description: 'El flujo de aprobación incluye revisión, comentarios y firma digital del gerente.',
        instructions: [
          'Desde la vista gerencial, revisá las solicitudes enviadas',
          'Abrí una solicitud para ver todos sus detalles y adjuntos',
          'Dejá comentarios o pedí correcciones si es necesario',
          'Para aprobar: hacé clic en "Aprobar" y firmá digitalmente',
          'La firma digital queda grabada con fecha y hora en el registro',
          'El solicitante recibe la notificación de aprobación',
        ],
        tips: [
          'Las solicitudes rechazadas incluyen el motivo para que el jefe de sitio pueda corregir y reenviar',
          'La firma digital del gerente es requisito para generar el certificado definitivo',
        ],
      },
    ],
  },
];