export const GENERAL_MODULES = [
  {
    id: 'dashboard',
    icon: '📊',
    title: 'Panel Principal (Dashboard)',
    description: 'Visualizá el estado general del negocio en un solo lugar',
    color: '#3b82f6',
    category: 'operaciones',
    keywords: ['inicio', 'resumen', 'métricas', 'gráficos', 'kpi'],
    steps: [
      {
        title: 'Acceder al Dashboard',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'El Dashboard es tu centro de control. Verás un resumen completo con KPIs, alertas, emergencias activas, pendientes SAP y el estado financiero.',
        instructions: [
          'Hacé clic en "Dashboard" en el menú lateral',
          'Observá los indicadores KPI en la parte superior',
          'Revisá el widget de Emergencias activas',
          'Chequeá los pendientes SAP y las OTs próximas',
          'Mirá los gráficos de ingresos y rentabilidad',
        ],
        tips: [
          'El dashboard se actualiza automáticamente en tiempo real',
          'Las tarjetas rojas requieren atención urgente',
        ],
        example: 'Si hay 2 emergencias activas, el widget parpadeará en rojo. Hacé clic para ir directo al módulo de emergencias.',
      },
      {
        title: 'Interpretar alertas y notificaciones',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema genera alertas automáticas sobre proyectos atrasados, stock bajo, facturas vencidas y mantenimientos.',
        instructions: [
          'Observá la campana de notificaciones en el header',
          'Lee las alertas de stock bajo en el banner superior',
          'Revisá las OTs vencidas destacadas en el dashboard',
          'Hacé clic en cualquier alerta para ir al módulo correspondiente',
        ],
        tips: [
          'Las alertas rojas son críticas, amarillas son advertencias, verdes son avisos',
          'Los proyectos con fecha límite próxima generan alertas automáticas de 3 niveles',
        ],
      },
    ],
  },
  {
    id: 'calendario',
    icon: '📅',
    title: 'Calendario',
    description: 'Visualizá OTs, informes y mantenimientos programados en un calendario mensual',
    color: '#6366f1',
    category: 'operaciones',
    keywords: ['calendario', 'fechas', 'agenda', 'programado', 'ots'],
    steps: [
      {
        title: 'Navegar el calendario',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El calendario muestra en una vista mensual todas las órdenes de trabajo, informes y mantenimientos de activos programados.',
        instructions: [
          'Andá a Calendario en el menú lateral',
          'Navegá entre meses con las flechas',
          'Hacé clic en un día para ver sus eventos',
          'Hacé clic en un evento para ver el detalle completo',
          'Usá el panel lateral para ver "Hoy" y "Próximos 7 días"',
        ],
        tips: [
          'Los colores identifican el tipo y prioridad: rojo = urgente, naranja = alta, azul = media',
          'Podés editar la fecha de una OT directamente desde el panel de detalle',
        ],
      },
    ],
  },
  {
    id: 'emergencias',
    icon: '🚨',
    title: 'Centro de Emergencias',
    description: 'Registrá y gestioná emergencias en establecimientos en tiempo real',
    color: '#ef4444',
    category: 'operaciones',
    keywords: ['emergencias', 'urgencias', 'incendio', 'inundacion', 'respuesta', 'alerta'],
    steps: [
      {
        title: 'Registrar una emergencia',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Permite reportar situaciones críticas y asignar cuadrillas de respuesta inmediata. Al crear una emergencia se genera automáticamente una OT urgente.',
        instructions: [
          'Andá a 🚨 Emergencias en el menú lateral',
          'Hacé clic en "Nueva Emergencia"',
          'Seleccioná el tipo (incendio, inundación, corte eléctrico, derrumbe, rotura gas, etc.)',
          'Buscá y seleccioná el establecimiento afectado',
          'Completá título y descripción de la situación',
          'Ingresá datos de contacto del reportante',
          'Subí fotos si las tenés disponibles',
          'Hacé clic en "Registrar Emergencia"',
        ],
        tips: [
          'El sistema crea automáticamente una OT de emergencia vinculada',
          'Las emergencias activas aparecen en el Dashboard con alerta roja',
        ],
        important: 'Al registrar una emergencia se genera automáticamente una Orden de Trabajo con prioridad urgente.',
      },
      {
        title: 'Gestionar estados y resolución',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Seguí el ciclo de vida de cada emergencia hasta su resolución.',
        instructions: [
          'Desde la lista, hacé clic en la emergencia a gestionar',
          'Cambiá el estado a "En Atención" cuando se despacha la cuadrilla',
          'Registrá el jefe de sitio asignado',
          'Al resolver, cambiá el estado a "Resuelta"',
          'Agregá notas de resolución',
          'El sistema calcula automáticamente el tiempo de respuesta',
        ],
        tips: [
          'Usá el tab "Dashboard" dentro de Emergencias para ver estadísticas históricas',
          'Las emergencias resueltas quedan archivadas con todos sus datos',
        ],
      },
    ],
  },
];