export const OPERACIONES_MODULES = [
  {
    id: 'proyectos',
    icon: '🏗️',
    title: 'Gestión de Proyectos',
    description: 'Creá, organizá y controlá todos tus proyectos de construcción',
    color: '#10b981',
    category: 'operaciones',
    keywords: ['proyectos', 'obras', 'timeline', 'presupuesto', 'avance'],
    steps: [
      {
        title: 'Crear un nuevo proyecto',
        duration: '5 min',
        difficulty: 'Básica',
        description: 'Los proyectos son el núcleo del negocio. Cada uno contiene información sobre la obra, cliente, equipo y presupuesto.',
        instructions: [
          'Andá a Proyectos en el menú lateral',
          'Hacé clic en "Nuevo Proyecto"',
          'Completá: nombre, código, cliente, dirección',
          'Definí el tipo (obra nueva, remodelación, mantenimiento, etc.)',
          'Establecé fechas de inicio y fin estimadas',
          'Definí el presupuesto estimado',
          'Establecé el % de avance inicial (0)',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Las fechas de inicio/fin permiten que el sistema calcule el avance esperado',
          'Las fechas realistas generan alertas correctas',
        ],
        example: 'Proyecto: "Remodelación Escuela Nº 5 - San Telmo" | Inicio: 01/05/2025 | Fin: 30/08/2025 | $2.500.000',
      },
      {
        title: 'Alertas automáticas de proyectos',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema analiza el % de avance real vs el esperado y genera alertas de 3 niveles automáticamente.',
        instructions: [
          'Abrí la página de Proyectos',
          'Observá los banners de alerta en la parte superior',
          'Verde: faltan 30-60 días y el avance está por debajo del esperado',
          'Amarillo: faltan 15-30 días con avance moderadamente bajo',
          'Rojo: faltan menos de 15 días o la fecha ya venció',
          'Podés cerrar cada alerta individualmente con la X',
        ],
        tips: [
          'El avance "esperado" se calcula en base al tiempo transcurrido desde el inicio',
          'Actualizá el % de avance regularmente para que las alertas sean precisas',
        ],
        important: 'Si la fecha de fin ya pasó y el proyecto no está completado, aparece alerta roja crítica.',
      },
    ],
  },
  {
    id: 'ordenes',
    icon: '📋',
    title: 'Órdenes de Trabajo (OT)',
    description: 'Creá y seguí órdenes de trabajo para tareas específicas en campo',
    color: '#f59e0b',
    category: 'operaciones',
    keywords: ['órdenes', 'ot', 'tareas', 'mantenimiento', 'qr', 'campo'],
    steps: [
      {
        title: 'Crear una orden de trabajo',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Las OTs son tareas concretas asignadas a técnicos. Pueden vincularse a proyectos, ubicaciones QR o emergencias.',
        instructions: [
          'Andá a Órdenes de Trabajo',
          'Hacé clic en "Nueva Orden"',
          'Seleccioná el proyecto asociado',
          'Definí el tipo (mantenimiento, instalación, reparación, emergencia, etc.)',
          'Asigná un técnico responsable',
          'Establecé fecha y horas estimadas',
          'Definí la prioridad (baja, media, alta, urgente)',
          'Opcionalmente vinculá una ubicación QR',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Las OTs urgentes aparecen destacadas en el dashboard',
          'Si la OT surge de una emergencia, se crea automáticamente',
        ],
        example: 'OT: "Reparación cañería rota - Escuela Nº12" | Urgente | Juan García | 4 hs',
      },
      {
        title: 'Ejecutar OT desde campo (móvil)',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Los técnicos ejecutan las OTs desde su celular: checklist, fotos, materiales y firma digital.',
        instructions: [
          'El técnico accede a la URL /ejecutar-ot en su celular',
          'Escanea o ingresa el código de la OT',
          'Ve el detalle completo de la tarea',
          'Completa el checklist ítem por ítem',
          'Sube fotos del trabajo realizado',
          'Registra materiales utilizados con cantidad',
          'Firma digitalmente al finalizar',
          'Hace clic en "Completar"',
        ],
        tips: [
          'Funciona sin internet (modo offline) y sincroniza cuando hay conexión',
          'Las fotos y firma quedan guardadas permanentemente',
        ],
        important: 'La firma digital es obligatoria para marcar una OT como completada.',
      },
      {
        title: 'Generar y usar QR de OT',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Cada OT tiene su propio QR para acceso rápido desde campo.',
        instructions: [
          'Abrí la OT',
          'Hacé clic en el ícono QR',
          'Descargá o imprimí el código',
          'Pegalo en el lugar físico de trabajo',
          'El técnico lo escanea para acceder directo',
        ],
        tips: [
          'Imprimí los QR y pegados en tableros o equipos de obra',
        ],
      },
    ],
  },
  {
    id: 'pendientes',
    icon: '📌',
    title: 'Pendientes SAP',
    description: 'Gestioná y seguí las órdenes SAP del ministerio',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['sap', 'pendientes', 'órdenes', 'establecimiento', 'jefe sitio'],
    steps: [
      {
        title: 'Ver y filtrar pendientes',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Los pendientes SAP son tareas provenientes del sistema ministerial que deben ejecutarse.',
        instructions: [
          'Andá a Pendientes en el menú lateral',
          'Usá los filtros por estado, jefe de sitio, prioridad, commune',
          'Buscá por número SAP, descripción o establecimiento',
          'Hacé clic en un pendiente para ver su detalle',
          'Revisá el historial de cambios de cada pendiente',
        ],
        tips: [
          'Los pendientes vencidos se marcan automáticamente en rojo',
          'Importá pendientes masivamente desde un Excel SAP',
        ],
      },
      {
        title: 'Asignar y actualizar pendientes',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Asigná jefes de sitio, cuadrillas y seguí el progreso hasta su resolución.',
        instructions: [
          'Abrí el pendiente a gestionar',
          'Asigná el jefe de sitio responsable',
          'Agregá la cuadrilla de trabajo',
          'Cambiá el estado: Pendiente → Asignado → En Progreso → Resuelto',
          'Registrá notas de resolución y fotos al finalizar',
        ],
        tips: [
          'Cada cambio de estado queda registrado en el historial para auditoría',
        ],
        important: 'Todo cambio de estado queda registrado en el Historial de Pendientes.',
      },
    ],
  },
  {
    id: 'informes',
    icon: '📄',
    title: 'Informes',
    description: 'Creá y gestioná informes de avance y situación de obras',
    color: '#0ea5e9',
    category: 'operaciones',
    keywords: ['informes', 'avance', 'reporte', 'documentos', 'situación'],
    steps: [
      {
        title: 'Crear un informe',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Los informes documentan el estado de situación de obras, inspecciones y actividades de campo.',
        instructions: [
          'Andá a Informes',
          'Hacé clic en "Nuevo Informe"',
          'Completá título y descripción',
          'Seleccioná el proyecto asociado',
          'Definí responsable y fecha límite',
          'Establecé prioridad y estado',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Los informes con fecha límite aparecen en el Calendario',
          'Podés cambiar el estado del informe (borrador, en revisión, aprobado)',
        ],
      },
    ],
  },
  {
    id: 'reportes',
    icon: '📈',
    title: 'Reportes & KPIs',
    description: 'Analizá el rendimiento operativo y financiero con gráficos interactivos',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['reportes', 'kpis', 'análisis', 'gráficos', 'tendencias'],
    steps: [
      {
        title: 'Explorar reportes operativos',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Los reportes y KPIs muestran el rendimiento del negocio con gráficos de tendencias, eficiencia y cumplimiento.',
        instructions: [
          'Andá a Reportes & KPIs',
          'Seleccioná la categoría de reporte',
          'Definí el rango de fechas',
          'Observá los gráficos interactivos',
          'Descargá en PDF o Excel si necesitás',
        ],
        tips: [
          'Compará períodos para detectar tendencias',
          'Los KPIs de OTs muestran tiempo real vs estimado',
        ],
      },
    ],
  },
  {
    id: 'rutinas',
    icon: '🔄',
    title: 'Rutinas de Mantenimiento (Anexo 3)',
    description: 'Gestioná el catálogo de rutinas preventivas y su ejecución por edificio',
    color: '#6366f1',
    category: 'operaciones',
    keywords: ['rutinas', 'mantenimiento', 'anexo 3', 'dgmesc', 'sismesc', 'edificios', 'preventivo'],
    steps: [
      {
        title: 'Conocer el catálogo de rutinas',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'El catálogo contiene 96 rutinas preventivas del PETP DGMESC (CABA), organizadas por rubro y frecuencia de ejecución.',
        instructions: [
          'Andá a Rutinas de Mantenimiento en el menú lateral',
          'Abrí la pestaña "Catálogo"',
          'Explorás las rutinas agrupadas por rubro (Electricidad, Plomería, Climatización, etc.)',
          'Cada rutina muestra: objeto, ciclo (semanal, mensual, anual), plazo y acciones',
          'Revisá el panel "Anexo 3" con la documentación de Mantenimiento vs TOM y regla del 50%',
          'Filtrá por rubro o buscá por palabra clave',
        ],
        tips: [
          'Las rutinas con "requiere_informe_matriculado" exigen firma de profesional habilitado',
          'Las rutinas con "carga_sismesc" requieren adjuntar comprobante en SISMESC',
          'La estacionalidad indica en qué meses aplica cada rutina (ej: climatización en invierno)',
        ],
        important: 'El catálogo distingue entre Mantenimiento (rutina preventiva) y TOM (Trabajo de Obra Mayor) que deriva en obra.',
      },
      {
        title: 'Sincronizar edificios y asignar rutinas',
        duration: '5 min',
        difficulty: 'Media',
        description: 'El sistema sincroniza automáticamente los edificios desde Información General y les asigna las rutinas aplicables del catálogo.',
        instructions: [
          'Abrí la pestaña "Sincronizar" dentro de Rutinas',
          'El sistema detecta edificios sin rutinas asignadas',
          'Hacé clic en "Sincronizar Edificios" para crear los faltantes',
          'Luego "Asignar Rutinas" para asociar el catálogo completo a cada edificio',
          'El proceso se ejecuta en lotes para evitar saturar el sistema',
          'Revisá el resumen final con la cantidad de edificios y rutinas asignadas',
        ],
        tips: [
          'La sincronización se basa en los establecimientos activos de Información General',
          'Podés asignar o desactivar rutinas individuales por edificio en la pestaña "Asignación"',
        ],
      },
      {
        title: 'Ejecutar y derivar órdenes de rutina',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Las órdenes de rutina se generan automáticamente según la frecuencia de cada rutina. Podés ejecutarlas, derivarlas a TOM o generar OTs consolidadas.',
        instructions: [
          'Abrí la pestaña "Tablero" para ver las órdenes pendientes y vencidas',
          'Filtrá por estado, ciclo, edificio o rubro',
          'Hacé clic en una orden para ver el detalle completo',
          'Para ejecutar: cargá la fecha, matrícula (si requiere) y adjuntá comprobantes SISMESC',
          'Si la rutina deriva en obra mayor, cambiá el estado a "Derivada a TOM"',
          'Usá "Generar OTs" para consolidar rutinas pendientes en una Orden de Trabajo por edificio',
        ],
        tips: [
          'El semáforo de vencimiento indica urgencia: verde, amarillo, rojo',
          'Las OTs consolidadas agrupan todas las rutinas pendientes de un edificio en una sola orden',
          'El tablero de Jefe de Sitio muestra las rutinas agrupadas por establecimiento',
        ],
        important: 'Las rutinas con "requiere_informe_matriculado" no se pueden marcar como ejecutadas sin cargar la matrícula profesional.',
      },
    ],
  },
  {
    id: 'foro',
    icon: '💬',
    title: 'Foro del Equipo',
    description: 'Comunicación interna del equipo: anuncios, consultas y discusiones',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['foro', 'comunicación', 'anuncios', 'equipo', 'mensajes', 'notificaciones'],
    steps: [
      {
        title: 'Participar en el foro',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El foro centraliza la comunicación del equipo con categorías temáticas, encuestas y reacciones.',
        instructions: [
          'Andá a Foro en el menú lateral',
          'Explorá las categorías disponibles en el panel lateral',
          'Hacé clic en un hilo para leer la conversación',
          'Respondé con el botón "Responder"',
          'Agregá reacciones con los emojis en cada mensaje',
          'Mencioná a compañeros con @nombre',
        ],
        tips: [
          'Los anuncios tienen fondo destacado y solo los admins pueden crearlos',
          'La campana 🔔 en el foro muestra tus menciones y respuestas',
          'Las encuestas permiten tomar decisiones colectivas',
        ],
      },
      {
        title: 'Crear un hilo o anuncio',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Publicá un hilo nuevo para una consulta, novedad o propuesta.',
        instructions: [
          'Hacé clic en "Nuevo Hilo"',
          'Elegí la categoría temática',
          'Ingresá título y cuerpo del mensaje',
          'Adjuntá imágenes o archivos si es necesario',
          'Opcionalmente creá una encuesta con el botón "Agregar encuesta"',
          'Publicá el hilo',
        ],
        tips: [
          'Usá los anuncios para comunicados importantes que deben verse destacados',
          'Podés fijar un hilo para que aparezca siempre arriba',
        ],
      },
    ],
  },
];