export const RECURSOS_MODULES = [
  {
    id: 'informacion-general',
    icon: '🏫',
    title: 'Información General',
    description: 'Administrá establecimientos, direcciones y jefes de sitio',
    color: '#f97316',
    category: 'campo',
    keywords: ['establecimientos', 'escuelas', 'direcciones', 'jefes', 'sitio', 'comunas'],
    steps: [
      {
        title: 'Directorio de establecimientos',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Centraliza todos los establecimientos (escuelas) y su estructura jerárquica de responsables.',
        instructions: [
          'Andá a Información General',
          'Navegá por la pestaña "Directorio"',
          'Buscá por nombre, dirección o jefe de sitio',
          'Filtrá por commune (8A, 8B, 10A)',
          'Hacé clic en una dirección para ver sus establecimientos',
        ],
        tips: [
          'Estructura: Dirección → Jefe de Sitio → Inspector → Establecimientos',
          'Usá la barra de búsqueda para encontrar cualquier escuela',
        ],
      },
      {
        title: 'Importar establecimientos',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Cargá datos masivos de establecimientos y jefes de sitio desde archivos Excel.',
        instructions: [
          'Andá a Información General > pestaña "Importar"',
          'Seleccioná el tipo de importación',
          'Descargá la plantilla de ejemplo',
          'Completá la plantilla con los datos',
          'Subí el archivo Excel',
          'Revisá el resumen y confirmá la carga',
        ],
        tips: [
          'Siempre usá la plantilla de ejemplo para el formato correcto',
        ],
      },
    ],
  },
  {
    id: 'empleados',
    icon: '👷',
    title: 'Empleados',
    description: 'Administrá el equipo operativo: roles, especialidades y datos',
    color: '#14b8a6',
    category: 'campo',
    keywords: ['empleados', 'equipo', 'roles', 'especialidades', 'cuadrilla'],
    steps: [
      {
        title: 'Agregar un empleado',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Registrá los datos de cada integrante del equipo operativo.',
        instructions: [
          'Andá a Empleados',
          'Hacé clic en "Nuevo Empleado"',
          'Completá: nombre, DNI, teléfono',
          'Seleccioná rol: operario, técnico, capataz, supervisor, etc.',
          'Elegí especialidad: electricidad, plomería, albañilería, etc.',
          'Definí estado (activo, licencia, vacaciones, inactivo)',
          'Establecé tarifa horaria',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Guardá el contacto de emergencia de cada empleado',
          'La asignación automática sugiere empleados por especialidad',
        ],
        example: 'Empleado: "Carlos Rodríguez" | Técnico | Electricidad | $2.800/hora',
      },
    ],
  },
  {
    id: 'mapa',
    icon: '🗺️',
    title: 'Mapa de Ubicaciones',
    description: 'Visualizá ubicaciones de obras y gestioná puntos QR de acceso',
    color: '#06b6d4',
    category: 'campo',
    keywords: ['mapa', 'gps', 'ubicaciones', 'qr', 'seguimiento'],
    steps: [
      {
        title: 'Gestionar ubicaciones en el mapa',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'El mapa interactivo muestra obras y ubicaciones activas. Podés crear puntos QR para uso en campo.',
        instructions: [
          'Andá a Mapa de Ubicaciones',
          'Observá los marcadores de ubicaciones activas',
          'Hacé clic en un marcador para ver detalles',
          'Para crear una nueva ubicación, usá el panel "Administración"',
          'Completá: nombre, dirección, tipo de evento (entrada/salida/ambos)',
          'Generá el QR de la ubicación y pegalo en el lugar físico',
        ],
        tips: [
          'Los marcadores verdes son ubicaciones activas',
          'Hacé clic derecho en el mapa para crear una ubicación en ese punto exacto',
        ],
      },
    ],
  },
  {
    id: 'mapa-jefes',
    icon: '🗺️',
    title: 'Mapa Jefes de Sitio',
    description: 'Visualizá la distribución geográfica de establecimientos por jefe de sitio',
    color: '#8b5cf6',
    category: 'campo',
    keywords: ['mapa', 'jefes', 'sitio', 'escuelas', 'comunas', 'distribución'],
    steps: [
      {
        title: 'Explorar el mapa de jefes',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Muestra la distribución geográfica de establecimientos agrupados por jefe de sitio o commune.',
        instructions: [
          'Andá a Mapa Jefes de Sitio',
          'Seleccioná el modo: Por Jefe, Por Commune o Clusters',
          'Cada color representa un jefe de sitio diferente',
          'Hacé clic en un marcador para ver las escuelas de esa dirección',
          'Usá el buscador para filtrar por jefe o dirección',
        ],
        tips: [
          'El modo "Clusters" agrupa ubicaciones cercanas para mejor visibilidad',
          'Podés importar datos desde Excel con el botón "Importar"',
        ],
      },
    ],
  },
  {
    id: 'inventario',
    icon: '📦',
    title: 'Inventario',
    description: 'Controlá stock de materiales y herramientas con movimientos del pañol',
    color: '#10b981',
    category: 'administracion',
    keywords: ['stock', 'materiales', 'inventario', 'pañol', 'movimientos'],
    steps: [
      {
        title: 'Registrar materiales',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Creá un registro para cada material o herramienta que manejás.',
        instructions: [
          'Andá a Inventario',
          'Hacé clic en "Nuevo Material"',
          'Completá: nombre, código, categoría, unidad',
          'Establecé stock inicial y stock mínimo (genera alertas)',
          'Escribí el costo unitario',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'El stock mínimo genera alertas automáticas en el dashboard',
          'Importá materiales masivamente desde Excel',
        ],
        example: 'Material: "Cable 2.5mm" | ELEC001 | metros | Stock mín: 100m',
      },
      {
        title: 'Registrar movimientos',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Todo movimiento queda registrado con fecha, responsable y motivo.',
        instructions: [
          'Abrí el material',
          'Hacé clic en "Nuevo Movimiento"',
          'Seleccioná entrada o salida',
          'Ingresá cantidad, motivo y responsable',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'El historial completo está en la pestaña "Historial"',
        ],
      },
    ],
  },
  {
    id: 'inspeccion-colegio',
    icon: '🔍',
    title: 'Inspección de Colegios',
    description: 'Realizá recorridos de inspección edilicia con voz, fotos e informe IA automático',
    color: '#3b82f6',
    category: 'campo',
    keywords: ['inspección', 'colegio', 'escuela', 'informe', 'ia', 'voz', 'fotos', 'recorrido'],
    steps: [
      {
        title: 'Crear una nueva inspección',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Registrá los datos del establecimiento a inspeccionar para iniciar el recorrido.',
        instructions: [
          'Andá a Inspección de Colegios en el menú lateral',
          'Hacé clic en "Nueva Inspección"',
          'Ingresá el establecimiento, dirección, jefe de sitio y fecha',
          'Agregá la commune si corresponde',
          'Hacé clic en "Crear Inspección"',
          'El sistema crea automáticamente las secciones estándar del recorrido',
        ],
        tips: [
          'El jefe de sitio se completa automáticamente si estás logueado con tu usuario',
          'Podés agregar secciones personalizadas además de las estándar',
        ],
      },
      {
        title: 'Documentar cada sección',
        duration: '5 min',
        difficulty: 'Básica',
        description: 'Completá cada sección del recorrido con notas de voz, texto y fotos.',
        instructions: [
          'Abrí la inspección creada',
          'Hacé clic en una sección (ej: "Baños", "Aulas", "Techos")',
          'Usá el botón de micrófono para dictar observaciones por voz',
          'Complementá con notas escritas si necesitás',
          'Subí fotos directamente desde la cámara del celular',
          'Asigná el nivel de urgencia: 🔴 Urgente, 🟡 Importante, 🟢 Leve',
          'Marcá la sección como "Completada" cuando termines',
          'Reordenás las secciones arrastrándolas si necesitás',
        ],
        tips: [
          'La grabación de voz transcribe automáticamente tus observaciones',
          'Podés agregar secciones personalizadas con el botón "Agregar sección"',
          'El nivel de urgencia 🔴 prioriza el ítem en el informe final',
        ],
        important: 'Completá todas las secciones antes de generar el informe para obtener un resultado más preciso.',
      },
      {
        title: 'Generar informe IA y crear OTs',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'La IA genera un informe técnico profesional y puede crear órdenes de trabajo automáticamente.',
        instructions: [
          'Con las secciones completadas, hacé clic en "Generar Informe"',
          'Esperá unos segundos mientras la IA procesa toda la información',
          'Revisá el informe generado con tablas de hallazgos y plan de acción',
          'Descargá el PDF profesional si necesitás',
          'Hacé clic en "Generar OTs" para crear órdenes de trabajo automáticamente',
          'Revisá las OTs propuestas, editá lo que necesites',
          'Confirmá la creación — las OTs quedan en estado Pendiente',
        ],
        tips: [
          'El informe incluye resumen ejecutivo, tablas de hallazgos y plan de acción priorizado',
          'Las OTs generadas heredan la prioridad del nivel de urgencia asignado',
          'Podés copiar el texto del informe para pegarlo en otro sistema',
        ],
        important: 'Las OTs generadas automáticamente quedan en "Pendiente" y aparecen en el módulo de Órdenes de Trabajo.',
      },
    ],
  },
  {
    id: 'calefaccion',
    icon: '🔥',
    title: 'Relevamiento de Calefacción',
    description: 'Registrá y analizá el estado de equipos de calefacción por escuela',
    color: '#f97316',
    category: 'campo',
    keywords: ['calefacción', 'estufas', 'calderas', 'radiadores', 'vrv', 'relevamiento', 'operativo'],
    steps: [
      {
        title: 'Registrar equipos de calefacción',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Cargá el relevamiento de equipos por escuela indicando cantidades funcionales y no funcionales.',
        instructions: [
          'Andá a Calefacción en el menú lateral',
          'Hacé clic en "Nuevo Relevamiento"',
          'Seleccioná el establecimiento y commune',
          'Elegí el tipo de equipo (estufas, radiadores, calderas, VRV, etc.)',
          'Ingresá cantidad total, cuántos funcionan y cuántos no',
          'El sistema calcula automáticamente el % operativo y el estado',
          'Agregá observaciones si es necesario',
          'Guardá el registro',
        ],
        tips: [
          'El estado se calcula automáticamente: Óptimo ≥90%, Normal 70-89%, Alerta 50-69%, Crítico <50%',
          'Importá relevamientos masivos desde Excel con el botón "Importar"',
          'Podés editar cualquier registro haciendo clic en él desde la tabla',
        ],
        example: 'Escuela N°5: 20 estufas | 15 funcionan | 5 no funcionan | 75% operativo → Estado: Normal',
      },
      {
        title: 'Analizar el estado global',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Visualizá el estado de calefacción de todos los establecimientos con métricas y alertas.',
        instructions: [
          'En el módulo Calefacción, observá el resumen de KPIs en la parte superior',
          'Filtrá por commune (8A, 8B, 10A) para ver por zona',
          'Los registros en rojo (Crítico) requieren atención inmediata',
          'Usá la búsqueda para encontrar un establecimiento específico',
          'Exportá datos desde la tabla si necesitás reportar',
        ],
        tips: [
          'Los registros críticos generan alertas automáticas en el sistema',
          'El período permite registrar relevamientos mensuales y comparar históricos',
        ],
      },
    ],
  },
  {
    id: 'control-riesgo',
    icon: '⚠️',
    title: 'Control de Riesgos',
    description: 'Identificá, evaluá y controlá riesgos operativos con la matriz de riesgo',
    color: '#ef4444',
    category: 'campo',
    keywords: ['riesgos', 'matriz', 'probabilidad', 'consecuencia', 'control', 'seguridad'],
    steps: [
      {
        title: 'Registrar un riesgo',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Documentá riesgos identificados en campo o en operaciones con su evaluación y método de control.',
        instructions: [
          'Andá a Control de Riesgos en el menú lateral',
          'Hacé clic en "Nuevo Riesgo"',
          'Completá: título, descripción, sector, establecimiento',
          'Elegí la probabilidad (1=Raro a 5=Casi certero)',
          'Elegí la consecuencia (1=Insignificante a 5=Catastrófico)',
          'El sistema calcula automáticamente el nivel: Aceptable / Tolerable / Alto / Extremo',
          'Definí el método de control (MP, MC, MT según corresponda)',
          'Establecé frecuencia de control y responsable',
          'Guardá el riesgo',
        ],
        tips: [
          'Nivel = Probabilidad × Consecuencia: <4 Aceptable, 4-15 Tolerable, 16-31 Alto, ≥32 Extremo',
          'Los riesgos Extremos y Altos generan alertas automáticas',
          'MP = Mantenimiento Preventivo, MC = Correctivo, MT = Matriculado (profesional habilitado)',
        ],
        important: 'Los riesgos con nivel Extremo requieren intervención inmediata y aparecen en el Dashboard.',
      },
    ],
  },
];