export const TUTORIAL_MODULES = [
  // ─── OPERACIONES ───────────────────────────────────────────────
  {
    id: 'dashboard',
    icon: '📊',
    title: 'Panel Principal (Dashboard)',
    description: 'Visualizá el estado general de tu negocio en un solo lugar',
    color: '#3b82f6',
    category: 'operaciones',
    keywords: ['inicio', 'resumen', 'métricas', 'gráficos', 'kpi'],
    steps: [
      {
        title: 'Acceder al Dashboard',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'El Dashboard es tu centro de control. Al iniciar sesión verás un resumen completo: KPIs, alertas, emergencias activas, pendientes SAP y mucho más.',
        instructions: [
          'Hacé clic en "Inicio" en el menú lateral',
          'Observá los indicadores (KPIs) en la parte superior',
          'Revisá el widget de Emergencias activas',
          'Chequeá los pendientes SAP y OTs próximas',
          'Mirá los gráficos de ingresos en la sección financiera',
        ],
        tips: [
          'El dashboard se actualiza automáticamente en tiempo real',
          'Las tarjetas rojas requieren atención urgente',
        ],
        example: 'Si hay 2 emergencias activas, el widget parpadeará en rojo. Hacé clic para ir directo al módulo de emergencias.',
      },
      {
        title: 'Interpretar alertas y notificaciones',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema genera alertas automáticas sobre proyectos atrasados, stock bajo, facturas vencidas y mantenimientos programados.',
        instructions: [
          'Observá la campana de notificaciones en el header',
          'Lee las alertas de stock bajo (materiales por debajo del mínimo)',
          'Revisá las OTs vencidas destacadas en el dashboard',
          'Hacé clic en una alerta para ir al módulo correspondiente',
        ],
        tips: [
          'Las alertas rojas son críticas, amarillas son advertencias',
          'En Proyectos también aparecen alertas por avance vs tiempo',
        ],
        important: 'Los proyectos con fecha límite próxima y avance bajo generan alertas automáticas en verde, amarillo o rojo.',
      },
    ],
  },
  {
    id: 'proyectos',
    icon: '🏗️',
    title: 'Gestión de Proyectos',
    description: 'Creá, organizá y controlá todos tus proyectos de construcción',
    color: '#10b981',
    category: 'operaciones',
    keywords: ['proyectos', 'obras', 'timeline', 'presupuesto', 'avance'],
    steps: [
      {
        title: 'Crear un nuevo proyecto',
        duration: '5 min',
        difficulty: 'Básica',
        description: 'Los proyectos son el núcleo de tu negocio. Cada uno contiene información sobre la obra, cliente, equipo y presupuesto.',
        instructions: [
          'Andá a Proyectos en el menú lateral',
          'Hacé clic en "Nuevo Proyecto"',
          'Completá: nombre, código, cliente, dirección',
          'Definí el tipo (obra nueva, remodelación, mantenimiento, etc.)',
          'Establecé fechas de inicio y fin estimadas',
          'Definí el presupuesto estimado',
          'Establecé el % de avance inicial (generalmente 0)',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Los nombres descriptivos facilitan identificar proyectos',
          'Las fechas realistas permiten que el sistema genere alertas correctas',
        ],
        example: 'Proyecto: "Remodelación Escuela Nº 5 - San Telmo" | Inicio: 01/05/2025 | Fin: 30/08/2025 | Presupuesto: $2.500.000',
      },
      {
        title: 'Sistema de alertas automáticas',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema analiza el % de avance real vs el esperado según el tiempo transcurrido y genera alertas de 3 niveles.',
        instructions: [
          'Abrí la página de Proyectos',
          'Observá los banners de alerta en la parte superior de la lista',
          'Verde (Aviso): faltan 30-60 días y el avance está por debajo del esperado',
          'Amarillo (Precaución): faltan 15-30 días con avance moderadamente bajo',
          'Rojo (Crítico): faltan menos de 15 días o la fecha ya venció',
          'Podés cerrar cada alerta con la X',
        ],
        tips: [
          'El avance "esperado" se calcula automáticamente en base al tiempo transcurrido',
          'Actualizá el % de avance regularmente para que las alertas sean precisas',
        ],
        important: 'Si la fecha de fin ya pasó y el proyecto no está completado, aparece una alerta roja crítica automáticamente.',
      },
      {
        title: 'Monitorear y actualizar progreso',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Mantené el control del avance del proyecto en tiempo real.',
        instructions: [
          'Hacé clic en un proyecto para ver su detalle',
          'Actualizá el porcentaje de avance en el formulario',
          'Revisá los datos de equipo y documentos adjuntos',
          'Chequeá las OTs asociadas al proyecto',
          'Descargá reportes si es necesario',
        ],
        tips: [
          'Actualizá el % de avance al menos una vez por semana',
          'Un proyecto "en_progreso" con 0% de avance por mucho tiempo generará alertas',
        ],
      },
    ],
  },
  {
    id: 'ordenes',
    icon: '📋',
    title: 'Órdenes de Trabajo (OT)',
    description: 'Creá y seguí órdenes de trabajo para tareas específicas en campo',
    color: '#f59e0b',
    category: 'operaciones',
    keywords: ['órdenes', 'ot', 'tareas', 'mantenimiento', 'urgencias', 'qr'],
    steps: [
      {
        title: 'Crear una orden de trabajo',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Las OTs son tareas concretas asignadas a técnicos. Pueden estar vinculadas a proyectos, ubicaciones QR o emergencias.',
        instructions: [
          'Andá a Órdenes de Trabajo',
          'Hacé clic en "Nueva Orden"',
          'Seleccioná el proyecto asociado',
          'Definí el tipo (mantenimiento, instalación, reparación, emergencia, etc.)',
          'Asigná un técnico responsable',
          'Establecé fecha y estimado de horas',
          'Definí la prioridad (baja, media, alta, urgente)',
          'Opcionalmente vinculá una ubicación QR',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Las OTs urgentes aparecen destacadas en el dashboard',
          'Si la OT surge de una emergencia, se crea automáticamente',
        ],
        example: 'OT: "Reparación cañería rota - Escuela Nº12" | Prioridad: Urgente | Asignado: Juan García | 4 horas estimadas',
      },
      {
        title: 'Ejecutar OT desde el campo (móvil)',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Los técnicos pueden ejecutar las OTs desde su celular: completar checklist, sacar fotos, ingresar materiales y firmar digitalmente.',
        instructions: [
          'El técnico escanea el QR de la OT desde su celular',
          'Ve el detalle completo de la tarea asignada',
          'Completa el checklist ítem por ítem',
          'Sube fotos del trabajo realizado',
          'Registra materiales utilizados con cantidad',
          'Firma digitalmente al finalizar',
          'Hace clic en "Guardar y Completar"',
        ],
        tips: [
          'Funciona sin internet (modo offline), sincroniza cuando hay conexión',
          'Las fotos quedan guardadas permanentemente en el sistema',
        ],
        important: 'La firma digital es obligatoria para marcar una OT como completada.',
      },
      {
        title: 'Generar y usar QR de OT',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Cada OT tiene su propio código QR que permite acceso rápido desde campo sin necesidad de buscar en el sistema.',
        instructions: [
          'Abrí la OT',
          'Hacé clic en el ícono QR',
          'Descargá o imprimí el código',
          'Pegalo en el lugar físico de trabajo',
          'El técnico lo escanea para acceder directo a la OT',
        ],
        tips: [
          'Imprimí los QR y pegados en tableros o equipos de obra',
          'Al escanear, el técnico ve todo: checklist, fotos requeridas, firma',
        ],
      },
    ],
  },
  {
    id: 'emergencias',
    icon: '🚨',
    title: 'Centro de Emergencias',
    description: 'Registrá y gestioná emergencias en establecimientos en tiempo real',
    color: '#ef4444',
    category: 'operaciones',
    keywords: ['emergencias', 'urgencias', 'incendio', 'inundacion', 'respuesta', 'alerta'],
    steps: [
      {
        title: 'Registrar una emergencia',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El módulo de emergencias permite reportar situaciones críticas y asignar cuadrillas de respuesta inmediata.',
        instructions: [
          'Andá a Emergencias en el menú lateral',
          'Hacé clic en "Nueva Emergencia"',
          'Seleccioná el tipo (incendio, inundación, corte eléctrico, derrumbe, rotura de gas, etc.)',
          'Buscá y seleccioná el establecimiento afectado',
          'Completá el título y la descripción de la situación',
          'Ingresá datos de contacto del reportante',
          'Subí fotos de la situación si las tenés',
          'Hacé clic en "Registrar Emergencia"',
        ],
        tips: [
          'El sistema crea automáticamente una OT de emergencia vinculada',
          'Las emergencias activas aparecen en el dashboard en tiempo real',
        ],
        important: 'Al registrar una emergencia, se genera automáticamente una Orden de Trabajo con prioridad urgente.',
      },
      {
        title: 'Gestionar estados y resolución',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Seguí el ciclo de vida de cada emergencia desde que se reporta hasta su resolución.',
        instructions: [
          'Desde la lista de emergencias, abrí la que querés gestionar',
          'Cambiá el estado a "En Atención" cuando se despacha cuadrilla',
          'Registrá el jefe de sitio asignado',
          'Cuando se resuelve, cambiá a "Resuelta"',
          'Agregá notas de resolución y tiempo de respuesta',
        ],
        tips: [
          'El sistema calcula automáticamente el tiempo de respuesta',
          'Usá el Dashboard de Emergencias para ver estadísticas históricas',
        ],
      },
    ],
  },
  {
    id: 'pendientes',
    icon: '📌',
    title: 'Pendientes SAP',
    description: 'Gestioná y hacé seguimiento de órdenes SAP y trabajos pendientes',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['sap', 'pendientes', 'órdenes', 'seguimiento', 'establecimiento'],
    steps: [
      {
        title: 'Ver y filtrar pendientes',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Los pendientes SAP son tareas que vienen del sistema SAP del ministerio y que deben ser ejecutadas por los equipos.',
        instructions: [
          'Andá a Activos > pestaña "Pendientes SAP"',
          'Usá los filtros por estado, jefe de sitio, comunidad, prioridad',
          'Buscá por número SAP, descripción o establecimiento',
          'Hacé clic en un pendiente para ver su detalle completo',
          'Podés ver el historial de cambios de estado de cada pendiente',
        ],
        tips: [
          'Los pendientes vencidos se marcan automáticamente en rojo',
          'El filtro por jefe de sitio es muy útil para ver la carga de trabajo',
        ],
      },
      {
        title: 'Asignar y actualizar pendientes',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Asigná jefes de sitio, cuadrillas y seguí el progreso de cada pendiente.',
        instructions: [
          'Abrí el pendiente que querés gestionar',
          'Asigná el jefe de sitio responsable',
          'Agregá la cuadrilla de trabajo',
          'Cambiá el estado: Pendiente → Asignado → En Progreso → Resuelto',
          'Registrá notas de resolución y fotos al finalizar',
          'Cada cambio de estado queda registrado en el historial',
        ],
        tips: [
          'Agregá comentarios en cada cambio de estado para tener trazabilidad',
          'Podés importar pendientes masivamente desde un archivo SAP',
        ],
        important: 'Todo cambio de estado queda registrado en el Historial de Pendientes para auditoría.',
      },
    ],
  },

  // ─── ADMINISTRACIÓN ────────────────────────────────────────────
  {
    id: 'clientes',
    icon: '👥',
    title: 'Proveedores y Clientes',
    description: 'Administrá información y relaciones con proveedores y clientes',
    color: '#ec4899',
    category: 'administracion',
    keywords: ['clientes', 'proveedores', 'contactos', 'valoración', 'rubro'],
    steps: [
      {
        title: 'Agregar un proveedor/cliente',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El módulo de Clientes gestiona tanto proveedores de materiales y servicios como clientes de la empresa.',
        instructions: [
          'Andá a Proveedores',
          'Hacé clic en "Nuevo"',
          'Completá: nombre/razón social, CUIT',
          'Seleccioná el rubro principal',
          'Agregá contacto con email y teléfono',
          'Asigná una valoración del 1 al 5',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'La valoración te ayuda a priorizar proveedores de confianza',
          'Usá las notas para registrar condiciones de pago o acuerdos especiales',
        ],
        example: 'Proveedor: "Ferreterías del Sur" | Rubro: Materiales | Valoración: ★★★★☆',
      },
    ],
  },
  {
    id: 'facturacion',
    icon: '💰',
    title: 'Facturación',
    description: 'Creá y gestioná facturas, presupuestos y registros de cobranza',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['facturas', 'dinero', 'pagos', 'cobranza', 'invoices'],
    steps: [
      {
        title: 'Crear una factura',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Las facturas formalizan los cobros a tus clientes y quedan registradas para el seguimiento financiero.',
        instructions: [
          'Andá a Facturación',
          'Hacé clic en "Nueva Factura"',
          'Seleccioná el cliente',
          'Agregá ítems con descripción, cantidad y precio unitario',
          'El total se calcula automáticamente',
          'Establecé fecha de vencimiento',
          'Hacé clic en "Guardar" y luego "Emitir"',
        ],
        tips: [
          'Verificá que el cliente sea correcto antes de emitir',
          'Exportá a PDF para enviar al cliente',
        ],
        important: 'Una vez emitida, la factura no se puede editar. Guardá siempre el PDF.',
      },
      {
        title: 'Registrar pagos',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Marcá los pagos recibidos de clientes para mantener las cuentas al día.',
        instructions: [
          'Abrí la factura pendiente',
          'Hacé clic en "Registrar Pago"',
          'Ingresá el monto pagado',
          'Seleccioná método (efectivo, transferencia, cheque)',
          'Agregá número de comprobante si existe',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Si el pago es parcial, el sistema calcula el saldo automáticamente',
          'Las facturas vencidas aparecen como alerta en el dashboard',
        ],
      },
    ],
  },
  {
    id: 'presupuestos',
    icon: '📐',
    title: 'Presupuestos de Obra',
    description: 'Creá presupuestos detallados usando el preciario ministerial',
    color: '#06b6d4',
    category: 'administracion',
    keywords: ['presupuesto', 'preciario', 'PCP', 'rubro', 'obra', 'coeficiente'],
    steps: [
      {
        title: 'Crear un presupuesto de obra',
        duration: '6 min',
        difficulty: 'Media',
        description: 'Los presupuestos de obra se arman en base al preciario ministerial, con ítems agrupados por rubro y cálculo automático de coeficientes.',
        instructions: [
          'Andá a Presupuestos de Obra',
          'Hacé clic en "Nuevo Presupuesto"',
          'Completá los datos de la obra: código, título, cliente, licitación',
          'Configurá los coeficientes de pase y oferta',
          'Seleccioná la commune del preciario',
          'En la grilla PCP, buscá ítems del preciario y agregálos',
          'Ingresá la cantidad para cada ítem',
          'El sistema calcula automáticamente los totales',
          'Exportá a Excel o genera el Plan de Trabajos',
        ],
        tips: [
          'Los ítems del preciario tienen código, descripción, unidad y precio base',
          'El coeficiente de pase por defecto es 1.6504 y el de oferta 1.38',
        ],
        important: 'Seleccioná la comuna correcta del preciario para que los precios sean los correspondientes.',
      },
      {
        title: 'Exportar y Plan de Trabajos',
        duration: '3 min',
        difficulty: 'Media',
        description: 'Una vez listo el presupuesto, podés exportar el PCP y generar automáticamente el Plan de Trabajos.',
        instructions: [
          'Desde el presupuesto, hacé clic en "Plan de Trabajos"',
          'El sistema distribuye automáticamente los ítems en semanas',
          'Ajustá la distribución si es necesario',
          'Hacé clic en "Exportar Excel" para el PCP completo',
          'El archivo Excel incluye todas las hojas reglamentarias',
        ],
        tips: [
          'El Plan de Trabajos puede editarse manualmente antes de exportar',
          'Los colores en el plan indican el % de distribución por período',
        ],
      },
    ],
  },
  {
    id: 'inventario',
    icon: '📦',
    title: 'Inventario y Pañol',
    description: 'Controlá stock de materiales, herramientas y movimientos del pañol',
    color: '#10b981',
    category: 'administracion',
    keywords: ['stock', 'materiales', 'inventario', 'pañol', 'herramientas', 'movimientos'],
    steps: [
      {
        title: 'Registrar materiales',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Creá un registro para cada material o herramienta que manejás en el pañol.',
        instructions: [
          'Andá a Inventario',
          'Hacé clic en "Nuevo Material"',
          'Completá: nombre, código, categoría',
          'Definí unidad de medida (metros, kilos, litros, unidades)',
          'Establecé stock inicial y stock mínimo',
          'Escribí el costo unitario',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'El stock mínimo genera alertas automáticas cuando se alcanza',
          'Los códigos únicos facilitan búsquedas y movimientos',
        ],
        example: 'Material: "Cable eléctrico 2.5mm" | Código: ELEC001 | Unidad: metros | Stock mín: 100m | Costo: $450/m',
      },
      {
        title: 'Registrar movimientos (entradas/salidas)',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Todo movimiento de stock queda registrado con fecha, responsable y motivo.',
        instructions: [
          'Abrí el material',
          'Hacé clic en "Nuevo Movimiento"',
          'Seleccioná tipo: entrada (compra/devolución) o salida (uso/asignación)',
          'Ingresá la cantidad',
          'Seleccioná el motivo',
          'Agregá el nombre del responsable',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Los movimientos de salida reducen el stock automáticamente',
          'El historial completo de movimientos está disponible en la pestaña "Historial"',
        ],
      },
    ],
  },

  // ─── CAMPO ─────────────────────────────────────────────────────
  {
    id: 'empleados',
    icon: '👷',
    title: 'Gestión de Empleados',
    description: 'Administrá datos, roles, especialidades y asistencia de tu equipo',
    color: '#14b8a6',
    category: 'campo',
    keywords: ['empleados', 'equipo', 'roles', 'especialidades', 'cuadrilla', 'qr'],
    steps: [
      {
        title: 'Agregar un empleado',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Registrá los datos principales de cada integrante del equipo operativo.',
        instructions: [
          'Andá a Empleados',
          'Hacé clic en "Nuevo Empleado"',
          'Completá: nombre, DNI, teléfono',
          'Seleccioná rol: operario, técnico, capataz, supervisor, etc.',
          'Elegí especialidad: electricidad, plomería, albañilería, etc.',
          'Definí estado (activo, licencia, vacaciones, inactivo)',
          'Establecé tarifa horaria',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Guardá el contacto de emergencia de cada empleado',
          'La asignación automática propone empleados por especialidad y disponibilidad',
        ],
        example: 'Empleado: "Carlos Rodríguez" | DNI: 28456789 | Rol: Técnico | Especialidad: Electricidad | $2.800/hora',
      },
      {
        title: 'Generar QR de empleado',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Cada empleado tiene un código QR único para registrar su asistencia desde campo.',
        instructions: [
          'Abrí el perfil del empleado',
          'Hacé clic en el ícono QR',
          'Descargá o imprimí el código',
          'Entregáselo al empleado para que lo tenga en su celular',
          'El empleado lo usa para fichar entrada/salida',
        ],
        tips: [
          'El código QR es personal e intransferible',
          'Guardalo como imagen de pantalla en el celular del empleado',
        ],
      },
    ],
  },
  {
    id: 'asistencia',
    icon: '⏰',
    title: 'Control de Asistencia (Fichar)',
    description: 'Registrá entrada y salida de empleados con GPS y firma digital',
    color: '#f43f5e',
    category: 'campo',
    keywords: ['asistencia', 'fichar', 'qr', 'gps', 'entrada', 'salida', 'firma'],
    steps: [
      {
        title: 'Fichar desde el móvil',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Los empleados registran entrada y salida usando su código QR personal, GPS y firma digital.',
        instructions: [
          'El empleado abre la URL de fichaje en su celular',
          'Va a la sección "Fichar"',
          'Muestra su código QR (o escanea el de la ubicación)',
          'Captura su firma digital en la pantalla',
          'Hacé clic en "Confirmar Entrada" o "Confirmar Salida"',
          'El sistema registra automáticamente GPS y hora',
        ],
        tips: [
          'La firma es obligatoria para validar el fichaje',
          'El GPS verifica que el empleado esté en la ubicación correcta',
        ],
        important: 'Sin firma válida, el fichaje no se registra. El empleado debe dibujar su firma en la pantalla.',
      },
      {
        title: 'Crear ubicaciones QR para fichaje',
        duration: '3 min',
        difficulty: 'Media',
        description: 'Configurá puntos de fichaje físicos con sus propios QR, ideal para obras con varios accesos.',
        instructions: [
          'Andá a Mapa > Gestión de Ubicaciones',
          'Hacé clic en "Nueva Ubicación"',
          'Completá: nombre, dirección, descripción',
          'Seleccioná tipo de evento: entrada, salida o ambos',
          'Elegí un color identificador',
          'Guardá y descargá el QR de esa ubicación',
          'Imprimilo y pegalo en el acceso de la obra',
        ],
        tips: [
          'Una obra grande puede tener múltiples puntos de fichaje',
          'Los empleados asignados a cada ubicación pueden verse en el panel de asignaciones',
        ],
      },
    ],
  },
  {
    id: 'mapa',
    icon: '🗺️',
    title: 'Mapa Interactivo',
    description: 'Visualizá ubicaciones de obras, fichajes y jefes de sitio en tiempo real',
    color: '#06b6d4',
    category: 'campo',
    keywords: ['mapa', 'gps', 'ubicaciones', 'jefes de sitio', 'seguimiento', 'escuelas'],
    steps: [
      {
        title: 'Mapa de Fichajes y Ubicaciones',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'El mapa interactivo muestra en tiempo real dónde están las obras y los fichajes de asistencia.',
        instructions: [
          'Andá a Mapa en el menú lateral',
          'Observá los marcadores de ubicaciones activas',
          'Hacé clic en un marcador para ver los detalles',
          'Cambiá a la pestaña "Fichajes" para ver los últimos registros de asistencia con GPS',
          'Usá la pestaña "Administración" para gestionar ubicaciones',
        ],
        tips: [
          'Los marcadores verdes son ubicaciones activas, los grises inactivos',
          'Hacé clic derecho en el mapa para crear una nueva ubicación en ese punto',
        ],
      },
      {
        title: 'Mapa de Jefes de Sitio',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Visualizá la distribución geográfica de establecimientos agrupados por jefe de sitio o comuna.',
        instructions: [
          'Andá a Mapa de Jefes en el menú lateral',
          'Seleccioná el modo de visualización: Por Jefe, Por Comuna o Clusters',
          'Cada color representa un jefe de sitio diferente',
          'Hacé clic en un marcador para ver las escuelas de esa dirección',
          'Usá el buscador para filtrar por nombre de jefe o dirección',
        ],
        tips: [
          'El modo "Clusters" agrupa ubicaciones cercanas para mejor visibilidad',
          'Podés importar datos de jefes y escuelas desde un Excel',
        ],
      },
    ],
  },

  // ─── REPORTES ─────────────────────────────────────────────────
  {
    id: 'reportes',
    icon: '📈',
    title: 'Reportes y Análisis',
    description: 'Generá reportes detallados de operaciones, finanzas y rendimiento',
    color: '#8b5cf6',
    category: 'reportes',
    keywords: ['reportes', 'análisis', 'datos', 'gráficos', 'export', 'pdf', 'excel'],
    steps: [
      {
        title: 'Reportes de proyectos y OTs',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Generá reportes sobre el estado, rentabilidad y cumplimiento de proyectos y órdenes.',
        instructions: [
          'Andá a Reportes',
          'Seleccioná la categoría: Proyectos, OTs, Empleados o Finanzas',
          'Definí el rango de fechas',
          'Aplicá filtros adicionales si es necesario',
          'Hacé clic en "Generar"',
          'Descargá en PDF o Excel',
        ],
        tips: [
          'Los gráficos muestran tendencias de forma visual',
          'Los reportes de OTs incluyen tiempo real vs estimado',
        ],
      },
      {
        title: 'Certificados de obra',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Generá certificados de avance de obra a partir de los presupuestos aprobados.',
        instructions: [
          'Andá a Certificados',
          'Seleccioná el presupuesto de obra base',
          'Ingresá el % de avance del período',
          'El sistema calcula el monto a certificar automáticamente',
          'Revisá los ítems certificados',
          'Exportá el certificado en PDF con firma',
        ],
        tips: [
          'Los certificados se generan sobre el presupuesto PCP aprobado',
          'Podés subir el ADA (acta de aprobación) desde el módulo de certificados',
        ],
      },
    ],
  },
  {
    id: 'informacion',
    icon: '🏫',
    title: 'Información General',
    description: 'Administrá establecimientos, direcciones y jefes de sitio',
    color: '#f97316',
    category: 'reportes',
    keywords: ['establecimientos', 'escuelas', 'direcciones', 'jefes', 'sitio', 'comunas'],
    steps: [
      {
        title: 'Directorio de establecimientos',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El módulo de Información General centraliza todos los establecimientos (escuelas) y su estructura jerárquica de responsables.',
        instructions: [
          'Andá a Información General',
          'Seleccioná la pestaña "Directorio"',
          'Buscá por nombre de establecimiento, dirección o jefe de sitio',
          'Filtrá por comuna (8A, 8B, 10A)',
          'Hacé clic en una dirección para ver sus establecimientos asociados',
          'Hacé clic en "Expandir" para ver el detalle completo',
        ],
        tips: [
          'La estructura es: Dirección → Jefe de Sitio → Inspector → Establecimientos',
          'Usá el campo de búsqueda para encontrar cualquier escuela rápidamente',
        ],
      },
      {
        title: 'Importar establecimientos',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Cargá datos masivos de establecimientos y jefes de sitio desde archivos Excel.',
        instructions: [
          'Andá a Información General > pestaña "Importar"',
          'Seleccioná el tipo de importación (Ubicaciones, Jefes, Escuelas, etc.)',
          'Descargá la plantilla de ejemplo',
          'Completá la plantilla con los datos',
          'Subí el archivo Excel',
          'Revisá el resumen de importación',
          'Confirmá la carga',
        ],
        tips: [
          'Siempre descargá y usá la plantilla de ejemplo para el formato correcto',
          'La importación no duplica registros existentes',
        ],
      },
    ],
  },
];