export const TUTORIAL_MODULES = [

  // ─── GENERAL ──────────────────────────────────────────────────
  {
    id: 'dashboard',
    icon: '📊',
    title: 'Panel Principal (Dashboard)',
    description: 'Visualizá el estado general del negocio en un solo lugar',
    color: '#3b82f6',
    category: 'operaciones',
    keywords: ['inicio', 'resumen', 'métricas', 'gráficos', 'kpi'],
    steps: [
      {
        title: 'Acceder al Dashboard',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'El Dashboard es tu centro de control. Verás un resumen completo con KPIs, alertas, emergencias activas, pendientes SAP y el estado financiero.',
        instructions: [
          'Hacé clic en "Dashboard" en el menú lateral',
          'Observá los indicadores KPI en la parte superior',
          'Revisá el widget de Emergencias activas',
          'Chequeá los pendientes SAP y las OTs próximas',
          'Mirá los gráficos de ingresos y rentabilidad',
        ],
        tips: [
          'El dashboard se actualiza automáticamente en tiempo real',
          'Las tarjetas rojas requieren atención urgente',
        ],
        example: 'Si hay 2 emergencias activas, el widget parpadeará en rojo. Hacé clic para ir directo al módulo de emergencias.',
      },
      {
        title: 'Interpretar alertas y notificaciones',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema genera alertas automáticas sobre proyectos atrasados, stock bajo, facturas vencidas y mantenimientos.',
        instructions: [
          'Observá la campana de notificaciones en el header',
          'Lee las alertas de stock bajo en el banner superior',
          'Revisá las OTs vencidas destacadas en el dashboard',
          'Hacé clic en cualquier alerta para ir al módulo correspondiente',
        ],
        tips: [
          'Las alertas rojas son críticas, amarillas son advertencias, verdes son avisos',
          'Los proyectos con fecha límite próxima generan alertas automáticas de 3 niveles',
        ],
      },
    ],
  },
  {
    id: 'calendario',
    icon: '📅',
    title: 'Calendario',
    description: 'Visualizá OTs, informes y mantenimientos programados en un calendario mensual',
    color: '#6366f1',
    category: 'operaciones',
    keywords: ['calendario', 'fechas', 'agenda', 'programado', 'ots'],
    steps: [
      {
        title: 'Navegar el calendario',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El calendario muestra en una vista mensual todas las órdenes de trabajo, informes y mantenimientos de activos programados.',
        instructions: [
          'Andá a Calendario en el menú lateral',
          'Navegá entre meses con las flechas',
          'Hacé clic en un día para ver sus eventos',
          'Hacé clic en un evento para ver el detalle completo',
          'Usá el panel lateral para ver "Hoy" y "Próximos 7 días"',
        ],
        tips: [
          'Los colores identifican el tipo y prioridad: rojo = urgente, naranja = alta, azul = media',
          'Podés editar la fecha de una OT directamente desde el panel de detalle',
        ],
      },
    ],
  },

  // ─── EMERGENCIAS ──────────────────────────────────────────────
  {
    id: 'emergencias',
    icon: '🚨',
    title: 'Centro de Emergencias',
    description: 'Registrá y gestioná emergencias en establecimientos en tiempo real',
    color: '#ef4444',
    category: 'operaciones',
    keywords: ['emergencias', 'urgencias', 'incendio', 'inundacion', 'respuesta', 'alerta'],
    steps: [
      {
        title: 'Registrar una emergencia',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Permite reportar situaciones críticas y asignar cuadrillas de respuesta inmediata. Al crear una emergencia se genera automáticamente una OT urgente.',
        instructions: [
          'Andá a 🚨 Emergencias en el menú lateral',
          'Hacé clic en "Nueva Emergencia"',
          'Seleccioná el tipo (incendio, inundación, corte eléctrico, derrumbe, rotura gas, etc.)',
          'Buscá y seleccioná el establecimiento afectado',
          'Completá título y descripción de la situación',
          'Ingresá datos de contacto del reportante',
          'Subí fotos si las tenés disponibles',
          'Hacé clic en "Registrar Emergencia"',
        ],
        tips: [
          'El sistema crea automáticamente una OT de emergencia vinculada',
          'Las emergencias activas aparecen en el Dashboard con alerta roja',
        ],
        important: 'Al registrar una emergencia se genera automáticamente una Orden de Trabajo con prioridad urgente.',
      },
      {
        title: 'Gestionar estados y resolución',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Seguí el ciclo de vida de cada emergencia hasta su resolución.',
        instructions: [
          'Desde la lista, hacé clic en la emergencia a gestionar',
          'Cambiá el estado a "En Atención" cuando se despacha la cuadrilla',
          'Registrá el jefe de sitio asignado',
          'Al resolver, cambiá el estado a "Resuelta"',
          'Agregá notas de resolución',
          'El sistema calcula automáticamente el tiempo de respuesta',
        ],
        tips: [
          'Usá el tab "Dashboard" dentro de Emergencias para ver estadísticas históricas',
          'Las emergencias resueltas quedan archivadas con todos sus datos',
        ],
      },
    ],
  },

  // ─── OPERACIONES ──────────────────────────────────────────────
  {
    id: 'proyectos',
    icon: '🏗️',
    title: 'Gestión de Proyectos',
    description: 'Creá, organizá y controlá todos tus proyectos de construcción',
    color: '#10b981',
    category: 'operaciones',
    keywords: ['proyectos', 'obras', 'timeline', 'presupuesto', 'avance'],
    steps: [
      {
        title: 'Crear un nuevo proyecto',
        duration: '5 min',
        difficulty: 'Básica',
        description: 'Los proyectos son el núcleo del negocio. Cada uno contiene información sobre la obra, cliente, equipo y presupuesto.',
        instructions: [
          'Andá a Proyectos en el menú lateral',
          'Hacé clic en "Nuevo Proyecto"',
          'Completá: nombre, código, cliente, dirección',
          'Definí el tipo (obra nueva, remodelación, mantenimiento, etc.)',
          'Establecé fechas de inicio y fin estimadas',
          'Definí el presupuesto estimado',
          'Establecé el % de avance inicial (0)',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Las fechas de inicio/fin permiten que el sistema calcule el avance esperado',
          'Las fechas realistas generan alertas correctas',
        ],
        example: 'Proyecto: "Remodelación Escuela Nº 5 - San Telmo" | Inicio: 01/05/2025 | Fin: 30/08/2025 | $2.500.000',
      },
      {
        title: 'Alertas automáticas de proyectos',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El sistema analiza el % de avance real vs el esperado y genera alertas de 3 niveles automáticamente.',
        instructions: [
          'Abrí la página de Proyectos',
          'Observá los banners de alerta en la parte superior',
          'Verde: faltan 30-60 días y el avance está por debajo del esperado',
          'Amarillo: faltan 15-30 días con avance moderadamente bajo',
          'Rojo: faltan menos de 15 días o la fecha ya venció',
          'Podés cerrar cada alerta individualmente con la X',
        ],
        tips: [
          'El avance "esperado" se calcula en base al tiempo transcurrido desde el inicio',
          'Actualizá el % de avance regularmente para que las alertas sean precisas',
        ],
        important: 'Si la fecha de fin ya pasó y el proyecto no está completado, aparece alerta roja crítica.',
      },
    ],
  },
  {
    id: 'ordenes',
    icon: '📋',
    title: 'Órdenes de Trabajo (OT)',
    description: 'Creá y seguí órdenes de trabajo para tareas específicas en campo',
    color: '#f59e0b',
    category: 'operaciones',
    keywords: ['órdenes', 'ot', 'tareas', 'mantenimiento', 'qr', 'campo'],
    steps: [
      {
        title: 'Crear una orden de trabajo',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Las OTs son tareas concretas asignadas a técnicos. Pueden vincularse a proyectos, ubicaciones QR o emergencias.',
        instructions: [
          'Andá a Órdenes de Trabajo',
          'Hacé clic en "Nueva Orden"',
          'Seleccioná el proyecto asociado',
          'Definí el tipo (mantenimiento, instalación, reparación, emergencia, etc.)',
          'Asigná un técnico responsable',
          'Establecé fecha y horas estimadas',
          'Definí la prioridad (baja, media, alta, urgente)',
          'Opcionalmente vinculá una ubicación QR',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Las OTs urgentes aparecen destacadas en el dashboard',
          'Si la OT surge de una emergencia, se crea automáticamente',
        ],
        example: 'OT: "Reparación cañería rota - Escuela Nº12" | Urgente | Juan García | 4 hs',
      },
      {
        title: 'Ejecutar OT desde campo (móvil)',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Los técnicos ejecutan las OTs desde su celular: checklist, fotos, materiales y firma digital.',
        instructions: [
          'El técnico accede a la URL /ejecutar-ot en su celular',
          'Escanea o ingresa el código de la OT',
          'Ve el detalle completo de la tarea',
          'Completa el checklist ítem por ítem',
          'Sube fotos del trabajo realizado',
          'Registra materiales utilizados con cantidad',
          'Firma digitalmente al finalizar',
          'Hace clic en "Completar"',
        ],
        tips: [
          'Funciona sin internet (modo offline) y sincroniza cuando hay conexión',
          'Las fotos y firma quedan guardadas permanentemente',
        ],
        important: 'La firma digital es obligatoria para marcar una OT como completada.',
      },
      {
        title: 'Generar y usar QR de OT',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Cada OT tiene su propio QR para acceso rápido desde campo.',
        instructions: [
          'Abrí la OT',
          'Hacé clic en el ícono QR',
          'Descargá o imprimí el código',
          'Pegalo en el lugar físico de trabajo',
          'El técnico lo escanea para acceder directo',
        ],
        tips: [
          'Imprimí los QR y pegados en tableros o equipos de obra',
        ],
      },
    ],
  },
  {
    id: 'pendientes',
    icon: '📌',
    title: 'Pendientes SAP',
    description: 'Gestioná y seguí las órdenes SAP del ministerio',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['sap', 'pendientes', 'órdenes', 'establecimiento', 'jefe sitio'],
    steps: [
      {
        title: 'Ver y filtrar pendientes',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Los pendientes SAP son tareas provenientes del sistema ministerial que deben ejecutarse.',
        instructions: [
          'Andá a Pendientes en el menú lateral',
          'Usá los filtros por estado, jefe de sitio, prioridad, commune',
          'Buscá por número SAP, descripción o establecimiento',
          'Hacé clic en un pendiente para ver su detalle',
          'Revisá el historial de cambios de cada pendiente',
        ],
        tips: [
          'Los pendientes vencidos se marcan automáticamente en rojo',
          'Importá pendientes masivamente desde un Excel SAP',
        ],
      },
      {
        title: 'Asignar y actualizar pendientes',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Asigná jefes de sitio, cuadrillas y seguí el progreso hasta su resolución.',
        instructions: [
          'Abrí el pendiente a gestionar',
          'Asigná el jefe de sitio responsable',
          'Agregá la cuadrilla de trabajo',
          'Cambiá el estado: Pendiente → Asignado → En Progreso → Resuelto',
          'Registrá notas de resolución y fotos al finalizar',
        ],
        tips: [
          'Cada cambio de estado queda registrado en el historial para auditoría',
        ],
        important: 'Todo cambio de estado queda registrado en el Historial de Pendientes.',
      },
    ],
  },
  {
    id: 'informes',
    icon: '📄',
    title: 'Informes',
    description: 'Creá y gestioná informes de avance y situación de obras',
    color: '#0ea5e9',
    category: 'operaciones',
    keywords: ['informes', 'avance', 'reporte', 'documentos', 'situación'],
    steps: [
      {
        title: 'Crear un informe',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Los informes documentan el estado de situación de obras, inspecciones y actividades de campo.',
        instructions: [
          'Andá a Informes',
          'Hacé clic en "Nuevo Informe"',
          'Completá título y descripción',
          'Seleccioná el proyecto asociado',
          'Definí responsable y fecha límite',
          'Establecé prioridad y estado',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Los informes con fecha límite aparecen en el Calendario',
          'Podés cambiar el estado del informe (borrador, en revisión, aprobado)',
        ],
      },
    ],
  },
  {
    id: 'reportes',
    icon: '📈',
    title: 'Reportes & KPIs',
    description: 'Analizá el rendimiento operativo y financiero con gráficos interactivos',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['reportes', 'kpis', 'análisis', 'gráficos', 'tendencias'],
    steps: [
      {
        title: 'Explorar reportes operativos',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Los reportes y KPIs muestran el rendimiento del negocio con gráficos de tendencias, eficiencia y cumplimiento.',
        instructions: [
          'Andá a Reportes & KPIs',
          'Seleccioná la categoría de reporte',
          'Definí el rango de fechas',
          'Observá los gráficos interactivos',
          'Descargá en PDF o Excel si necesitás',
        ],
        tips: [
          'Compará períodos para detectar tendencias',
          'Los KPIs de OTs muestran tiempo real vs estimado',
        ],
      },
    ],
  },

  // ─── COMERCIAL ────────────────────────────────────────────────
  {
    id: 'proveedores',
    icon: '🚛',
    title: 'Proveedores',
    description: 'Administrá el directorio de proveedores de materiales y servicios',
    color: '#ec4899',
    category: 'administracion',
    keywords: ['proveedores', 'contactos', 'valoración', 'rubro', 'cuit'],
    steps: [
      {
        title: 'Registrar un proveedor',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Mantené actualizado el directorio de proveedores con sus datos de contacto y valoración de desempeño.',
        instructions: [
          'Andá a Proveedores',
          'Hacé clic en "Nuevo"',
          'Completá: nombre/razón social, CUIT',
          'Seleccioná el rubro principal',
          'Agregá contacto, email y teléfono',
          'Asigná una valoración del 1 al 5',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'La valoración te ayuda a priorizar proveedores confiables',
          'Usá las notas para condiciones de pago o acuerdos especiales',
        ],
        example: 'Proveedor: "Ferreterías del Sur" | Rubro: Materiales | Valoración: ★★★★☆',
      },
    ],
  },
  {
    id: 'presupuestos',
    icon: '💵',
    title: 'Presupuestos',
    description: 'Creá cotizaciones y presupuestos para enviar a clientes',
    color: '#f97316',
    category: 'administracion',
    keywords: ['presupuesto', 'cotización', 'cliente', 'items', 'precio'],
    steps: [
      {
        title: 'Crear un presupuesto',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Los presupuestos son cotizaciones que se envían al cliente antes de iniciar un trabajo.',
        instructions: [
          'Andá a Presupuestos',
          'Hacé clic en "Nuevo Presupuesto"',
          'Seleccioná el cliente',
          'Agregá ítems con descripción, cantidad y precio unitario',
          'El total se calcula automáticamente',
          'Establecé fecha de validez',
          'Guardá y exportá en PDF para enviar',
        ],
        tips: [
          'Un presupuesto aprobado puede convertirse en factura',
          'Incluí márgenes razonables en los precios',
        ],
      },
    ],
  },
  {
    id: 'presupuestos-obra',
    icon: '📐',
    title: 'Presupuestos de Obra (PCP)',
    description: 'Creá presupuestos detallados usando el preciario ministerial',
    color: '#06b6d4',
    category: 'administracion',
    keywords: ['presupuesto', 'preciario', 'PCP', 'rubro', 'coeficiente', 'ministerio'],
    steps: [
      {
        title: 'Crear un presupuesto PCP',
        duration: '6 min',
        difficulty: 'Media',
        description: 'Los presupuestos PCP se arman en base al preciario ministerial, con ítems agrupados por rubro y cálculo automático de coeficientes.',
        instructions: [
          'Andá a Presupuestos Obra',
          'Hacé clic en "Nuevo Presupuesto"',
          'Completá: código, título, cliente, licitación, escuela',
          'Configurá los coeficientes de pase y oferta',
          'Seleccioná la commune del preciario',
          'En la grilla PCP, buscá ítems del preciario y agregálos',
          'Ingresá la cantidad para cada ítem',
          'El sistema calcula automáticamente los totales',
        ],
        tips: [
          'El coeficiente de pase por defecto es 1.6504 y el de oferta 1.38',
          'Podés agrupar ítems por rubros para organizar mejor el presupuesto',
        ],
        important: 'Seleccioná la commune correcta del preciario para que los precios sean los correspondientes.',
      },
      {
        title: 'Exportar y Plan de Trabajos',
        duration: '3 min',
        difficulty: 'Media',
        description: 'Exportá el PCP completo a Excel y generá automáticamente el Plan de Trabajos.',
        instructions: [
          'Desde el presupuesto, hacé clic en "Plan de Trabajos"',
          'El sistema distribuye automáticamente los ítems en semanas',
          'Ajustá la distribución si es necesario',
          'Hacé clic en "Exportar Excel" para el PCP completo',
        ],
        tips: [
          'El archivo Excel incluye todas las hojas reglamentarias',
          'El Plan de Trabajos puede editarse antes de exportar',
        ],
      },
    ],
  },
  {
    id: 'certificados',
    icon: '🏆',
    title: 'Certificados de Obra',
    description: 'Generá certificados de avance de obra a partir de presupuestos aprobados',
    color: '#eab308',
    category: 'administracion',
    keywords: ['certificados', 'avance', 'ada', 'obra', 'facturar'],
    steps: [
      {
        title: 'Generar un certificado',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Los certificados de obra documentan el avance ejecutado en un período y sirven de base para la facturación.',
        instructions: [
          'Andá a Certificados',
          'Seleccioná el presupuesto PCP base',
          'Ingresá el % de avance del período a certificar',
          'El sistema calcula el monto a certificar automáticamente',
          'Revisá los ítems certificados',
          'Exportá el certificado en PDF',
        ],
        tips: [
          'Podés subir el ADA (Acta de Aprobación) desde el módulo',
          'Los certificados se generan sobre el presupuesto PCP aprobado',
        ],
      },
    ],
  },
  {
    id: 'facturacion',
    icon: '💰',
    title: 'Facturación',
    description: 'Creá y gestioná facturas y registros de cobranza',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['facturas', 'pagos', 'cobranza', 'vencimiento'],
    steps: [
      {
        title: 'Crear una factura',
        duration: '5 min',
        difficulty: 'Media',
        description: 'Las facturas formalizan los cobros y quedan registradas para el seguimiento financiero.',
        instructions: [
          'Andá a Facturación',
          'Hacé clic en "Nueva Factura"',
          'Seleccioná el cliente',
          'Agregá ítems con descripción, cantidad y precio',
          'Establecé fecha de vencimiento',
          'Guardá y emitila',
        ],
        tips: [
          'Exportá en PDF para enviar al cliente',
          'Las facturas vencidas generan alerta en el dashboard',
        ],
        important: 'Una vez emitida, la factura no se puede editar. Guardá siempre el PDF.',
      },
      {
        title: 'Registrar pagos',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Marcá los pagos recibidos para mantener las cuentas al día.',
        instructions: [
          'Abrí la factura pendiente de cobro',
          'Hacé clic en "Registrar Pago"',
          'Ingresá el monto pagado y método',
          'Guardá',
        ],
        tips: [
          'Los pagos parciales calculan el saldo automáticamente',
        ],
      },
    ],
  },
  {
    id: 'finanzas',
    icon: '📊',
    title: 'Finanzas',
    description: 'Analizá el flujo de caja y la rentabilidad de proyectos',
    color: '#22c55e',
    category: 'administracion',
    keywords: ['finanzas', 'flujo', 'caja', 'rentabilidad', 'gastos', 'ingresos'],
    steps: [
      {
        title: 'Explorar el módulo de finanzas',
        duration: '4 min',
        difficulty: 'Media',
        description: 'El módulo de finanzas muestra el resumen financiero, flujo de caja y rentabilidad por proyecto.',
        instructions: [
          'Andá a Finanzas en el menú lateral',
          'Revisá el Resumen Financiero con ingresos y egresos',
          'Explorá el Flujo de Caja para ver movimientos en el tiempo',
          'Analizá la Rentabilidad por Proyecto',
          'Filtrá por período para ver distintos rangos',
        ],
        tips: [
          'Un margen sano está entre 20-30%',
          'Identificá proyectos menos rentables para optimizar costos',
        ],
      },
    ],
  },

  // ─── RECURSOS ─────────────────────────────────────────────────
  {
    id: 'informacion-general',
    icon: '🏫',
    title: 'Información General',
    description: 'Administrá establecimientos, direcciones y jefes de sitio',
    color: '#f97316',
    category: 'campo',
    keywords: ['establecimientos', 'escuelas', 'direcciones', 'jefes', 'sitio', 'comunas'],
    steps: [
      {
        title: 'Directorio de establecimientos',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Centraliza todos los establecimientos (escuelas) y su estructura jerárquica de responsables.',
        instructions: [
          'Andá a Información General',
          'Navegá por la pestaña "Directorio"',
          'Buscá por nombre, dirección o jefe de sitio',
          'Filtrá por commune (8A, 8B, 10A)',
          'Hacé clic en una dirección para ver sus establecimientos',
        ],
        tips: [
          'Estructura: Dirección → Jefe de Sitio → Inspector → Establecimientos',
          'Usá la barra de búsqueda para encontrar cualquier escuela',
        ],
      },
      {
        title: 'Importar establecimientos',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Cargá datos masivos de establecimientos y jefes de sitio desde archivos Excel.',
        instructions: [
          'Andá a Información General > pestaña "Importar"',
          'Seleccioná el tipo de importación',
          'Descargá la plantilla de ejemplo',
          'Completá la plantilla con los datos',
          'Subí el archivo Excel',
          'Revisá el resumen y confirmá la carga',
        ],
        tips: [
          'Siempre usá la plantilla de ejemplo para el formato correcto',
        ],
      },
    ],
  },
  {
    id: 'empleados',
    icon: '👷',
    title: 'Empleados',
    description: 'Administrá el equipo operativo: roles, especialidades y datos',
    color: '#14b8a6',
    category: 'campo',
    keywords: ['empleados', 'equipo', 'roles', 'especialidades', 'cuadrilla'],
    steps: [
      {
        title: 'Agregar un empleado',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Registrá los datos de cada integrante del equipo operativo.',
        instructions: [
          'Andá a Empleados',
          'Hacé clic en "Nuevo Empleado"',
          'Completá: nombre, DNI, teléfono',
          'Seleccioná rol: operario, técnico, capataz, supervisor, etc.',
          'Elegí especialidad: electricidad, plomería, albañilería, etc.',
          'Definí estado (activo, licencia, vacaciones, inactivo)',
          'Establecé tarifa horaria',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'Guardá el contacto de emergencia de cada empleado',
          'La asignación automática sugiere empleados por especialidad',
        ],
        example: 'Empleado: "Carlos Rodríguez" | Técnico | Electricidad | $2.800/hora',
      },
    ],
  },
  {
    id: 'mapa',
    icon: '🗺️',
    title: 'Mapa de Ubicaciones',
    description: 'Visualizá ubicaciones de obras y gestioná puntos QR de acceso',
    color: '#06b6d4',
    category: 'campo',
    keywords: ['mapa', 'gps', 'ubicaciones', 'qr', 'seguimiento'],
    steps: [
      {
        title: 'Gestionar ubicaciones en el mapa',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'El mapa interactivo muestra obras y ubicaciones activas. Podés crear puntos QR para uso en campo.',
        instructions: [
          'Andá a Mapa de Ubicaciones',
          'Observá los marcadores de ubicaciones activas',
          'Hacé clic en un marcador para ver detalles',
          'Para crear una nueva ubicación, usá el panel "Administración"',
          'Completá: nombre, dirección, tipo de evento (entrada/salida/ambos)',
          'Generá el QR de la ubicación y pegalo en el lugar físico',
        ],
        tips: [
          'Los marcadores verdes son ubicaciones activas',
          'Hacé clic derecho en el mapa para crear una ubicación en ese punto exacto',
        ],
      },
    ],
  },
  {
    id: 'mapa-jefes',
    icon: '🗺️',
    title: 'Mapa Jefes de Sitio',
    description: 'Visualizá la distribución geográfica de establecimientos por jefe de sitio',
    color: '#8b5cf6',
    category: 'campo',
    keywords: ['mapa', 'jefes', 'sitio', 'escuelas', 'comunas', 'distribución'],
    steps: [
      {
        title: 'Explorar el mapa de jefes',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Muestra la distribución geográfica de establecimientos agrupados por jefe de sitio o commune.',
        instructions: [
          'Andá a Mapa Jefes de Sitio',
          'Seleccioná el modo: Por Jefe, Por Commune o Clusters',
          'Cada color representa un jefe de sitio diferente',
          'Hacé clic en un marcador para ver las escuelas de esa dirección',
          'Usá el buscador para filtrar por jefe o dirección',
        ],
        tips: [
          'El modo "Clusters" agrupa ubicaciones cercanas para mejor visibilidad',
          'Podés importar datos desde Excel con el botón "Importar"',
        ],
      },
    ],
  },
  {
    id: 'inventario',
    icon: '📦',
    title: 'Inventario',
    description: 'Controlá stock de materiales y herramientas con movimientos del pañol',
    color: '#10b981',
    category: 'administracion',
    keywords: ['stock', 'materiales', 'inventario', 'pañol', 'movimientos'],
    steps: [
      {
        title: 'Registrar materiales',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Creá un registro para cada material o herramienta que manejás.',
        instructions: [
          'Andá a Inventario',
          'Hacé clic en "Nuevo Material"',
          'Completá: nombre, código, categoría, unidad',
          'Establecé stock inicial y stock mínimo (genera alertas)',
          'Escribí el costo unitario',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'El stock mínimo genera alertas automáticas en el dashboard',
          'Importá materiales masivamente desde Excel',
        ],
        example: 'Material: "Cable 2.5mm" | ELEC001 | metros | Stock mín: 100m',
      },
      {
        title: 'Registrar movimientos',
        duration: '2 min',
        difficulty: 'Básica',
        description: 'Todo movimiento queda registrado con fecha, responsable y motivo.',
        instructions: [
          'Abrí el material',
          'Hacé clic en "Nuevo Movimiento"',
          'Seleccioná entrada o salida',
          'Ingresá cantidad, motivo y responsable',
          'Hacé clic en "Guardar"',
        ],
        tips: [
          'El historial completo está en la pestaña "Historial"',
        ],
      },
    ],
  },

  // ─── CAMPO / INSPECCIONES ─────────────────────────────────────
  {
    id: 'inspeccion-colegio',
    icon: '🔍',
    title: 'Inspección de Colegios',
    description: 'Realizá recorridos de inspección edilicia con voz, fotos e informe IA automático',
    color: '#3b82f6',
    category: 'campo',
    keywords: ['inspección', 'colegio', 'escuela', 'informe', 'ia', 'voz', 'fotos', 'recorrido'],
    steps: [
      {
        title: 'Crear una nueva inspección',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Registrá los datos del establecimiento a inspeccionar para iniciar el recorrido.',
        instructions: [
          'Andá a Inspección de Colegios en el menú lateral',
          'Hacé clic en "Nueva Inspección"',
          'Ingresá el establecimiento, dirección, jefe de sitio y fecha',
          'Agregá la commune si corresponde',
          'Hacé clic en "Crear Inspección"',
          'El sistema crea automáticamente las secciones estándar del recorrido',
        ],
        tips: [
          'El jefe de sitio se completa automáticamente si estás logueado con tu usuario',
          'Podés agregar secciones personalizadas además de las estándar',
        ],
      },
      {
        title: 'Documentar cada sección',
        duration: '5 min',
        difficulty: 'Básica',
        description: 'Completá cada sección del recorrido con notas de voz, texto y fotos.',
        instructions: [
          'Abrí la inspección creada',
          'Hacé clic en una sección (ej: "Baños", "Aulas", "Techos")',
          'Usá el botón de micrófono para dictar observaciones por voz',
          'Complementá con notas escritas si necesitás',
          'Subí fotos directamente desde la cámara del celular',
          'Asigná el nivel de urgencia: 🔴 Urgente, 🟡 Importante, 🟢 Leve',
          'Marcá la sección como "Completada" cuando termines',
          'Reordenás las secciones arrastrándolas si necesitás',
        ],
        tips: [
          'La grabación de voz transcribe automáticamente tus observaciones',
          'Podés agregar secciones personalizadas con el botón "Agregar sección"',
          'El nivel de urgencia 🔴 prioriza el ítem en el informe final',
        ],
        important: 'Completá todas las secciones antes de generar el informe para obtener un resultado más preciso.',
      },
      {
        title: 'Generar informe IA y crear OTs',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'La IA genera un informe técnico profesional y puede crear órdenes de trabajo automáticamente.',
        instructions: [
          'Con las secciones completadas, hacé clic en "Generar Informe"',
          'Esperá unos segundos mientras la IA procesa toda la información',
          'Revisá el informe generado con tablas de hallazgos y plan de acción',
          'Descargá el PDF profesional si necesitás',
          'Hacé clic en "Generar OTs" para crear órdenes de trabajo automáticamente',
          'Revisá las OTs propuestas, editá lo que necesites',
          'Confirmá la creación — las OTs quedan en estado Pendiente',
        ],
        tips: [
          'El informe incluye resumen ejecutivo, tablas de hallazgos y plan de acción priorizado',
          'Las OTs generadas heredan la prioridad del nivel de urgencia asignado',
          'Podés copiar el texto del informe para pegarlo en otro sistema',
        ],
        important: 'Las OTs generadas automáticamente quedan en "Pendiente" y aparecen en el módulo de Órdenes de Trabajo.',
      },
    ],
  },
  {
    id: 'calefaccion',
    icon: '🔥',
    title: 'Relevamiento de Calefacción',
    description: 'Registrá y analizá el estado de equipos de calefacción por escuela',
    color: '#f97316',
    category: 'campo',
    keywords: ['calefacción', 'estufas', 'calderas', 'radiadores', 'vrv', 'relevamiento', 'operativo'],
    steps: [
      {
        title: 'Registrar equipos de calefacción',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Cargá el relevamiento de equipos por escuela indicando cantidades funcionales y no funcionales.',
        instructions: [
          'Andá a Calefacción en el menú lateral',
          'Hacé clic en "Nuevo Relevamiento"',
          'Seleccioná el establecimiento y commune',
          'Elegí el tipo de equipo (estufas, radiadores, calderas, VRV, etc.)',
          'Ingresá cantidad total, cuántos funcionan y cuántos no',
          'El sistema calcula automáticamente el % operativo y el estado',
          'Agregá observaciones si es necesario',
          'Guardá el registro',
        ],
        tips: [
          'El estado se calcula automáticamente: Óptimo ≥90%, Normal 70-89%, Alerta 50-69%, Crítico <50%',
          'Importá relevamientos masivos desde Excel con el botón "Importar"',
          'Podés editar cualquier registro haciendo clic en él desde la tabla',
        ],
        example: 'Escuela N°5: 20 estufas | 15 funcionan | 5 no funcionan | 75% operativo → Estado: Normal',
      },
      {
        title: 'Analizar el estado global',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Visualizá el estado de calefacción de todos los establecimientos con métricas y alertas.',
        instructions: [
          'En el módulo Calefacción, observá el resumen de KPIs en la parte superior',
          'Filtrá por commune (8A, 8B, 10A) para ver por zona',
          'Los registros en rojo (Crítico) requieren atención inmediata',
          'Usá la búsqueda para encontrar un establecimiento específico',
          'Exportá datos desde la tabla si necesitás reportar',
        ],
        tips: [
          'Los registros críticos generan alertas automáticas en el sistema',
          'El período permite registrar relevamientos mensuales y comparar históricos',
        ],
      },
    ],
  },
  {
    id: 'control-riesgo',
    icon: '⚠️',
    title: 'Control de Riesgos',
    description: 'Identificá, evaluá y controlá riesgos operativos con la matriz de riesgo',
    color: '#ef4444',
    category: 'campo',
    keywords: ['riesgos', 'matriz', 'probabilidad', 'consecuencia', 'control', 'seguridad'],
    steps: [
      {
        title: 'Registrar un riesgo',
        duration: '4 min',
        difficulty: 'Media',
        description: 'Documentá riesgos identificados en campo o en operaciones con su evaluación y método de control.',
        instructions: [
          'Andá a Control de Riesgos en el menú lateral',
          'Hacé clic en "Nuevo Riesgo"',
          'Completá: título, descripción, sector, establecimiento',
          'Elegí la probabilidad (1=Raro a 5=Casi certero)',
          'Elegí la consecuencia (1=Insignificante a 5=Catastrófico)',
          'El sistema calcula automáticamente el nivel: Aceptable / Tolerable / Alto / Extremo',
          'Definí el método de control (MP, MC, MT según corresponda)',
          'Establecé frecuencia de control y responsable',
          'Guardá el riesgo',
        ],
        tips: [
          'Nivel = Probabilidad × Consecuencia: <4 Aceptable, 4-15 Tolerable, 16-31 Alto, ≥32 Extremo',
          'Los riesgos Extremos y Altos generan alertas automáticas',
          'MP = Mantenimiento Preventivo, MC = Correctivo, MT = Matriculado (profesional habilitado)',
        ],
        important: 'Los riesgos con nivel Extremo requieren intervención inmediata y aparecen en el Dashboard.',
      },
    ],
  },
  {
    id: 'certificacion-obras',
    icon: '📋',
    title: 'Certificación de Obras',
    description: 'Controlá el avance y estado de cobro de obras en cada ciclo mensual',
    color: '#eab308',
    category: 'administracion',
    keywords: ['certificación', 'obras', 'avance', 'ciclo', 'cobro', 'MEIN', 'MTOM', 'SAP'],
    steps: [
      {
        title: 'Gestionar el ciclo de certificación',
        duration: '5 min',
        difficulty: 'Media',
        description: 'El módulo de Certificación de Obras centraliza el seguimiento de avance y estado de cobro de cada obra en el ciclo mensual activo.',
        instructions: [
          'Andá a Certificación de Obras',
          'Revisá las obras del ciclo activo',
          'Filtrá por commune, estado de cobro o jefe de sitio',
          'Hacé clic en una obra para editar su avance, estado y observaciones',
          'Los estados de cobro son: Listo Certificar, Faltan Actas, Pendiente, Observado, Falta Aprobar MEIN',
          'Al cerrar el ciclo, los registros se archivan automáticamente',
          'Importá obras nuevas desde Excel con el botón "Importar"',
        ],
        tips: [
          'Usá el campo "Tramo de certificación" para distinguir primer y segundo 50%',
          'Las obras observadas tienen un campo de motivo para documentar el problema',
          'Exportá el resumen del ciclo a PDF desde el botón de exportar',
        ],
      },
    ],
  },
  {
    id: 'aprobacion-certificados',
    icon: '✅',
    title: 'Aprobación de Certificados',
    description: 'Flujo de solicitud, revisión y firma gerencial de certificados de obra',
    color: '#22c55e',
    category: 'administracion',
    keywords: ['aprobación', 'firma', 'gerente', 'certificado', 'solicitud', 'digital'],
    steps: [
      {
        title: 'Crear una solicitud de certificado',
        duration: '4 min',
        difficulty: 'Básica',
        description: 'Los jefes de sitio envían solicitudes de certificado que luego revisa y aprueba gerencia.',
        instructions: [
          'Andá a Aprobación de Certificados',
          'Hacé clic en "Nueva Solicitud"',
          'Completá: título, establecimiento, período, descripción del trabajo',
          'Ingresá el monto solicitado y % de avance',
          'Adjuntá fotos y documentos de respaldo',
          'Hacé clic en "Enviar Solicitud"',
        ],
        tips: [
          'Las solicitudes enviadas llegan a la vista de revisión gerencial',
          'Podés guardar como borrador antes de enviar',
        ],
      },
      {
        title: 'Revisar y aprobar (gerencia)',
        duration: '3 min',
        difficulty: 'Media',
        description: 'El flujo de aprobación incluye revisión, comentarios y firma digital del gerente.',
        instructions: [
          'Desde la vista gerencial, revisá las solicitudes enviadas',
          'Abrí una solicitud para ver todos sus detalles y adjuntos',
          'Dejá comentarios o pedí correcciones si es necesario',
          'Para aprobar: hacé clic en "Aprobar" y firmá digitalmente',
          'La firma digital queda grabada con fecha y hora en el registro',
          'El solicitante recibe la notificación de aprobación',
        ],
        tips: [
          'Las solicitudes rechazadas incluyen el motivo para que el jefe de sitio pueda corregir y reenviar',
          'La firma digital del gerente es requisito para generar el certificado definitivo',
        ],
      },
    ],
  },
  {
    id: 'foro',
    icon: '💬',
    title: 'Foro del Equipo',
    description: 'Comunicación interna del equipo: anuncios, consultas y discusiones',
    color: '#8b5cf6',
    category: 'operaciones',
    keywords: ['foro', 'comunicación', 'anuncios', 'equipo', 'mensajes', 'notificaciones'],
    steps: [
      {
        title: 'Participar en el foro',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'El foro centraliza la comunicación del equipo con categorías temáticas, encuestas y reacciones.',
        instructions: [
          'Andá a Foro en el menú lateral',
          'Explorá las categorías disponibles en el panel lateral',
          'Hacé clic en un hilo para leer la conversación',
          'Respondé con el botón "Responder"',
          'Agregá reacciones con los emojis en cada mensaje',
          'Mencioná a compañeros con @nombre',
        ],
        tips: [
          'Los anuncios tienen fondo destacado y solo los admins pueden crearlos',
          'La campana 🔔 en el foro muestra tus menciones y respuestas',
          'Las encuestas permiten tomar decisiones colectivas',
        ],
      },
      {
        title: 'Crear un hilo o anuncio',
        duration: '3 min',
        difficulty: 'Básica',
        description: 'Publicá un hilo nuevo para una consulta, novedad o propuesta.',
        instructions: [
          'Hacé clic en "Nuevo Hilo"',
          'Elegí la categoría temática',
          'Ingresá título y cuerpo del mensaje',
          'Adjuntá imágenes o archivos si es necesario',
          'Opcionalmente creá una encuesta con el botón "Agregar encuesta"',
          'Publicá el hilo',
        ],
        tips: [
          'Usá los anuncios para comunicados importantes que deben verse destacados',
          'Podés fijar un hilo para que aparezca siempre arriba',
        ],
      },
    ],
  },

  // ─── ADMINISTRACIÓN ───────────────────────────────────────────
  {
    id: 'alertas',
    icon: '🔔',
    title: 'Alertas Proactivas',
    description: 'Configurá alertas automáticas por vencimientos, stock y pendientes',
    color: '#f59e0b',
    category: 'administracion',
    keywords: ['alertas', 'notificaciones', 'vencimiento', 'stock', 'automatico'],
    steps: [
      {
        title: 'Configurar alertas',
        duration: '4 min',
        difficulty: 'Media',
        description: 'El módulo de alertas proactivas te permite configurar notificaciones automáticas para distintos eventos del sistema.',
        instructions: [
          'Andá a Alertas Proactivas en Administración',
          'Activá o desactivá cada tipo de alerta',
          'Configurá los días de anticipación para vencimientos',
          'Establecé el umbral de stock mínimo',
          'Agregá emails destinatarios para notificaciones',
          'Guardá los cambios',
        ],
        tips: [
          'Las alertas pueden mostrarse como banner en el dashboard y/o enviarse por email',
          'Los tipos disponibles son: garantía de activo, stock bajo, pendiente vencido',
        ],
      },
    ],
  },
  {
    id: 'importar',
    icon: '📥',
    title: 'Importar Datos',
    description: 'Cargá datos masivos desde Excel o CSV al sistema',
    color: '#64748b',
    category: 'administracion',
    keywords: ['importar', 'excel', 'csv', 'masivo', 'carga'],
    steps: [
      {
        title: 'Importar datos desde Excel',
        duration: '5 min',
        difficulty: 'Media',
        description: 'El módulo de importación permite cargar grandes volúmenes de datos de cualquier módulo desde archivos Excel.',
        instructions: [
          'Andá a Importar Datos',
          'Seleccioná el tipo de datos a importar',
          'Descargá la plantilla de ejemplo',
          'Completá la plantilla con tus datos',
          'Subí el archivo en el paso "Subir archivo"',
          'Mapeá las columnas con los campos del sistema',
          'Revisá la vista previa',
          'Confirmá la importación',
        ],
        tips: [
          'Siempre usá la plantilla descargada para evitar errores de formato',
          'Podés importar empleados, materiales, proyectos, pendientes y más',
        ],
        important: 'Revisá siempre la vista previa antes de confirmar para detectar errores en los datos.',
      },
    ],
  },
];